import * as React from "react";
import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  AM_FINANCE_EN,
  AM_FINANCE_HY,
  AM_FINANCE_RU,
} from "./amFinance.i18n";
import {
  AM_FREELANCE_EN,
  AM_FREELANCE_HY,
  AM_FREELANCE_RU,
} from "./amFreelance.i18n";
import {
  AM_TRANSPORT_EN,
  AM_TRANSPORT_HY,
  AM_TRANSPORT_RU,
} from "./amTransport.i18n";

export type Language = 'en' | 'hy' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tWithParams: (key: string, params: { [key: string]: string | number }) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'app.title': 'Capital',
    'app.subtitle': 'Live rates & smart conversion',
    // App & Navigation    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.reorderCards': 'Sort cards',
    'dashboard.reorderCardsHint':
      'Drag the grip (⋮) on a tile to move it. Order is saved automatically.',
    'dashboard.finishReorder': 'Done',
    'dashboard.converter': 'Converter',
    'dashboard.multiCurrency': 'Multi Currency',
    'dashboard.rateAlerts': 'Rate Alerts',
    'dashboard.savedRates': 'Saved Rates',
    
    // Quick Actions
    'quick.action.converter': 'Currency Converter',
    'quick.action.converter.desc': 'Professional converter with all features',
    'quick.action.multiCurrency': 'Multi Currency',
    'quick.action.multiCurrency.desc': 'Quick conversions to 20 currencies',
    'quick.action.multiCurrency.hide': 'Hide conversion tool',
    'quick.action.rateAlerts': 'Rate Alerts',
    'quick.action.rateAlerts.desc': 'Set target rates for currency monitoring',
    'quick.action.rateAlerts.hide': 'Hide alerts',
    'quick.action.savedRates': 'Saved Rates',
    'quick.action.savedRates.desc': 'Quick access to favorites',
    'quick.action.savedRates.hide': 'Hide saved rates',
    'quick.action.settings': 'Settings',
    'quick.action.settings.desc': 'Account and app preferences',
    'quick.action.calculator': 'Quick Calculator',
    'quick.action.calculator.desc': 'Open basic math calculator',
    'quick.action.calculator.hide': 'Hide calculator widget',
    'quick.action.loanCalculator': 'Loan calculator',
    'quick.action.vacationCalc': 'Vacation pay',
    'quick.action.disabilityBenefit': 'Sick leave benefit',
    'quick.toolsMenu': 'Other tools',
    'quick.action.touristCalc': 'Tourist calculator',

    'touristCalc.share.title': 'Tourist calculator',
    'touristCalc.field.amount': 'Amount (foreign currency)',
    'touristCalc.field.currency': 'Currency',
    'touristCalc.field.rate': 'Exchange rate (to AMD)',
    'touristCalc.rate.auto': 'Rate is taken from updated market data',
    'touristCalc.rate.unavailable': 'Rate unavailable (refresh data)',
    'touristCalc.rate.manualToggle': 'Manual exchange rate',
    'touristCalc.rate.manualHint': 'Enter the exchange rate manually',
    'touristCalc.field.feePct': 'Fee (%)',
    'touristCalc.field.discountPct': 'Discount (%)',
    'touristCalc.field.tipPct': 'Tip (%)',
    'touristCalc.result.discount': 'Discount',
    'touristCalc.result.subtotal': 'Subtotal',
    'touristCalc.result.tip': 'Tip',
    'touristCalc.result.total': 'Total',
    'touristCalc.result.fee': 'Fee',
    'touristCalc.result.net': 'Net amount',
    'touristCalc.result.received': 'Amount received (AMD)',
    'touristCalc.invalid': 'Invalid input',
    
    // Currency Converter
    'converter.title': 'Currency Converter',
    'converter.subtitle': 'Complete currency conversion suite with advanced features',
    'converter.standard': 'Standard Conversion',
    'converter.multiCurrency.section': 'Multi-Currency',    'converter.saveRate': 'Save This Rate',
    'converter.disclaimer': 'Professional currency converter with real-time rates and advanced features',
    'converter.loadingRates': 'Loading exchange rates...',
    'converter.refreshData': 'Refresh Data',
    'converter.enterAmount': 'Enter amount to convert',
    'converter.exchangeRate': 'Exchange Rate',
    'converter.rate': 'Rate',
    'converter.to': 'To',
    'converter.from': 'From',
    'converter.selectCurrencies': 'Select currencies to see conversion',
    'converter.professional': 'Professional currency converter with real-time rates and advanced features',
    'converter.conversionResult': '{amount} {fromCurrency} = {convertedAmount} {toCurrency}',
    'converter.exchangeRateResult': '{rateLabel}: 1 {fromCurrency} = {rate} {toCurrency}',
    'converter.cbaRateNotice':
      'Official Central Bank of Armenia (cba.am) rate for {currencies}.',
    'converter.backToDashboard': '← Back to Dashboard',
    'converter.amountLabel': 'Amount',
    'converter.enterAmountPlaceholder': 'Enter amount',
    'converter.fromLabel': 'From',
    'converter.toLabel': 'To',
    'converter.placeholderResult': 'Enter an amount to see conversion',
    'converter.recentTitle': 'Recent',
    'converter.saveRateButton': 'Save',
    'converter.chartButton': 'Chart',
    'converter.saveSuccessTitle': 'Success',
    'converter.saveSuccessMessage': 'Rate saved to your account!',
    'converter.saveSuccessLocalMessage': 'Rate saved locally. Sign in to sync across devices!',
    'converter.saveErrorTitle': 'Error',
    'converter.saveErrorMessage': 'Failed to save rate. Please try again.',
    
    // Rate Alerts
    'alerts.title': 'Rate Alerts',
    'alerts.active': 'Your Active Alerts:',    // Rate Alert Manager
    'rateAlerts.signInRequired': 'Sign In Required',
    'rateAlerts.signInMessage': 'Please sign in to create rate alerts',
    'rateAlerts.error': 'Error',
    'rateAlerts.updateFailed': 'Failed to update rate alert',
    'rateAlerts.createFailed': 'Failed to create rate alert',
    'rateAlerts.success': 'Success',
    'rateAlerts.savedSuccessfully': 'Rate alert has been saved successfully!',
    'rateAlerts.deleteTitle': 'Delete Alert',
    'rateAlerts.deleteMessage': 'Are you sure you want to delete this rate alert?',
    'rateAlerts.cancelButton': 'Cancel',
    'rateAlerts.deleteButton': 'Delete',
    'rateAlerts.deleteFailed': 'Failed to delete rate alert',
    'rateAlerts.updateStatusFailed': 'Failed to update alert status',
    'rateAlerts.title': 'Rate Alerts',
    'rateAlerts.signInPrompt': 'Sign in to create and manage currency rate alerts!',
    'rateAlerts.loading': 'Loading...',
    'rateAlerts.errorPrefix': 'Error: {error}',
    'rateAlerts.createButton': '+ Create Alert',
    'rateAlerts.activeCount': '{count} active alerts',
    'rateAlerts.emptyState': 'No rate alerts yet. Create your first alert to get notified when rates reach your target!',
    'rateAlerts.active': 'Active',
    'rateAlerts.target': 'Target:',
    'rateAlerts.status': 'Status:',
    'rateAlerts.created': 'Created:',
    'rateAlerts.edit': 'Edit',
    'rateAlerts.delete': 'Delete',
    'rateAlerts.cancel': 'Cancel',
    'rateAlerts.editAlert': 'Edit Alert',
    'rateAlerts.createAlert': 'Create Alert',
    'rateAlerts.save': 'Save',
    'rateAlerts.fromCurrency': 'From Currency',
    'rateAlerts.toCurrency': 'To Currency',
    'rateAlerts.targetRate': 'Target Rate (1 {fromCurrency} = X {toCurrency})',
    'rateAlerts.enterRate': 'Enter rate for {fromCurrency} → {toCurrency}',
    'rateAlerts.direction': 'Direction',
    'rateAlerts.direction.above': 'above',
    'rateAlerts.direction.below': 'below',
    'rateAlerts.activateAlert': 'Activate Alert',
    'rateAlerts.status.inactive': 'Inactive',
    'rateAlerts.status.active': 'Active',
    'rateAlerts.status.notified': 'Notified',
    'rateAlerts.conditionAlreadyMetTitle': 'Alert Condition Already Met',
    'rateAlerts.conditionAlreadyMetMessage': 'The current rate for {fromCurrency} → {toCurrency} is {currentRate}, which is already {condition} your target of {targetRate}. The alert will trigger immediately.',
    'rateAlerts.createAnyway': 'Create Anyway',
    'rateAlerts.resetTitle': 'Reset Alert',
    'rateAlerts.resetMessage': 'Do you want to reset this alert? It will be able to trigger again when the condition is met.',
    'rateAlerts.resetButton': 'Reset',
    'rateAlerts.resetFailed': 'Failed to reset alert',
    'rateAlerts.reset': 'Reset',
    
    // Saved Rates
    'saved.title': 'Saved Rates',
    'saved.titles': 'Saved Rates', // Alias for compatibility
    'saved.shortTitle': 'Saved', // Short version for constrained layouts
    'saved.clear': 'Clear All',    'saved.deleteConfirm': 'Are you sure you want to delete this saved rate?',
    'saved.deleteAllConfirm': 'Are you sure you want to delete all saved rates? This action cannot be undone.',
    'saved.delete': 'Delete',
    'saved.cancel': 'Cancel',
    'saved.deleteAll': 'Delete All',
    'saved.noRates': 'No saved rates yet. Convert currencies and click "Save This Rate" to add some!',
    'saved.savedOn': 'Saved on',
    'saved.at': 'at',
    'saved.rate': 'saved rate',
    'saved.rates': 'saved rates',
    'alerts.activeAlert': 'active alert',
    'alerts.activeAlerts': 'active alerts',
    'success.rateSaved': 'Rate saved successfully!',
    'success.alertCreated': 'Rate alert created successfully!',
    'success.alertDeleted': 'Rate alert deleted',
    'success.rateDeleted': 'Rate deleted',
    'saved.deleteRateTitle': 'Delete Rate',
    'saved.deleteRateMessage': 'Are you sure you want to delete this saved rate?',
    'saved.deleteRateCancel': 'Cancel',
    'saved.deleteRateConfirm': 'Delete',
    'saved.deleteSuccessTitle': 'Success',
    'saved.deleteSuccessMessage': 'Rate deleted successfully',
    'saved.deleteFailedTitle': 'Delete Failed',
    'saved.deleteFailedMessage': 'Unable to delete the rate. Please try again or check your internet connection.',
    'saved.deleteErrorTitle': 'Error',
    'saved.deleteErrorMessage': 'An unexpected error occurred while deleting the rate.',
    'saved.deleteAllTitle': 'Delete All Rates',
    'saved.deleteAllMessage': 'Are you sure you want to delete all saved rates? This action cannot be undone.',
    'saved.deleteAllCancel': 'Cancel',
    'saved.deleteAllConfirmButton': 'Delete All',
    'saved.deleteAllErrorTitle': 'Error',
    'saved.deleteAllErrorMessage': 'Failed to delete all saved rates',
    'saved.signInPrompt': 'Sign in to save and sync your currency rates across devices!',
    'saved.emptyState': 'No saved rates yet. Convert currencies and click "Save This Rate" to add some!',
    'saved.loadingText': 'Loading saved rates...',
    'saved.deletingIcon': '⏳',
    'saved.deleteIcon': '',
    'saved.hideIcon': '×',    // Settings & Common
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and app preferences',
    'settings.accountInfo': 'Account Information',
    'settings.updateAccountInfo': 'Update Account Information',
    'settings.loginRequired': 'Please sign in to view your account information',
    'settings.password': 'Password',
    'settings.changePassword': 'Change Password',
    'settings.newPassword': 'New Password',
    'settings.confirmNewPassword': 'Confirm New Password',
    'settings.passwordUpdateDescription': 'Update your password to keep your account secure',
    'settings.termsOfUse': 'Terms of Use',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.preferences': 'Preferences',
    'settings.theme': 'Theme',
    'settings.system': 'System',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.appLock': 'App lock',
    'settings.appLockHint':
      'After the app was in the background, open it again with your device passcode, Face ID, Touch ID, or fingerprint—the same ways you unlock your phone.',
    'settings.dataManagement': 'Data Management',
    'settings.exchangeRateInfo': 'Exchange Rate Information',
    'settings.aboutExchangeRates': 'About Exchange Rates',
    'settings.exchangeRateInfoDescription':
      'Exchange rates refresh hourly. For currencies published by the Central Bank of Armenia, official cba.am rates apply to AMD pairs.',
    'settings.languageEnglish': 'English',
    'settings.languageArmenian': 'Armenian',
    'settings.languageRussian': 'Russian',
    'settings.clearCache': 'Clear Cache',
    'settings.clearAllData': 'Clear All Data',
    'settings.aboutSupport': 'About & Support',
    'settings.about': 'About',
    'settings.help': 'Help',
    'settings.contactSupport': 'Contact Support',
    'contactSupport.title': 'Contact Support',
    'contactSupport.describeIssue': 'Describe your issue:',
    'contactSupport.yourEmail': 'Your email (optional):',
    'contactSupport.sendMessage': 'Send Message',
    'contactSupport.messageSent': 'Your message has been sent successfully!',
    'contactSupport.sendError': 'Failed to send message. Please try again.',
    'contactSupport.emptyMessage': 'Please enter a message',
    'contactSupport.emailUnavailable': 'Email is not available on this device',
    'contactSupport.emailPlaceholder': 'your.email@example.com',
    'contactSupport.subject': 'Capital Support Request',
    'settings.dangerZone': 'Danger Zone',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountTitle': 'Delete account?',
    'settings.deleteAccountMessage':
      'Final confirmation: your account and all associated data will be permanently removed.',
    'settings.deleteAccountConfirm': 'Delete permanently',
    'settings.deleteAccountSuccessTitle': 'Account deleted',
    'settings.deleteAccountSuccessMessage': 'Your account and data on this device have been removed.',
    'settings.deleteAccountFailed':
      'Could not delete your account. If this persists, sign out and try again or contact support.',
    'settings.dangerZoneModalIntro':
      'Deleting your account permanently removes all personal data we hold for you on our servers and on this device.',
    'settings.dangerZoneModalBulletServer':
      'Cloud: saved rates, alerts, converter and calculator history, and related records.',
    'settings.dangerZoneModalBulletDevice':
      'This device: preferences, drafts, cache, dashboard layout, and other local data.',
    'settings.dangerZoneModalBulletIrreversible':
      'This cannot be undone. You can sign up again with the same email as a new, empty account.',
    'settings.dangerZoneModalBulletSupport':
      'Unsure? Contact support before you continue.',
    'settings.dangerZoneModalClose': 'Close',
    'settings.dangerZoneModalContactSupport': 'Contact support',
    'settings.deleteAccountFinalGoogle':
      'Final step: you will sign in with Google again to prove it is you, then your account will be removed.',
    'settings.deleteAccountFinalApple':
      'Final step: you will sign in with Apple again to prove it is you, then your account will be removed.',
    'settings.deleteAccountPasswordTitle': 'Confirm password',
    'settings.deleteAccountPasswordSubtitle':
      'Enter your account password to permanently delete this account.',
    'settings.deleteAccountPasswordPlaceholder': 'Password',
    'settings.deleteAccountPasswordEmpty': 'Please enter your password.',
    'settings.deleteAccountPasswordWrong': 'Incorrect password. Try again.',
    'settings.deleteAccountWrongOAuthAccount':
      'You signed in with a different account. Use the same Google or Apple account as in this app.',
    'settings.deleteAccountUnsupportedAuth':
      'This sign-in method cannot confirm account deletion in the app. Please contact support.',
    'settings.enableNotifications': 'Enable Notifications',
    'settings.sound': 'Sound',
    'settings.vibration': 'Vibration',
    'settings.showPreview': 'Show Preview',
    'appLock.unlockTitle': 'Unlock Capital',
    'appLock.unlockSubtitle':
      'Use the same screen lock you already use on this device—passcode, Face ID, Touch ID, or fingerprint.',
    'appLock.unlockButton': 'Unlock',
    'appLock.authPrompt': 'Unlock Capital',
    'appLock.notAvailable': 'Device authentication is not available.',
    'appLock.notEnrolled': 'Set up a screen lock, Face ID, Touch ID, or fingerprint on your device first.',
    'appLock.failed': 'Authentication did not succeed.',
    'appLock.webUnsupported': 'App lock is only available in the iOS and Android apps.',

    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.settings': 'Settings',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.close': 'Close',
    'common.share': 'Share',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',    'common.update': 'Update',    'common.more': 'More',    'common.showMore': 'Show More',
    'common.showLess': 'Show Less',    'common.selected': 'Selected',    // Multi-Currency
    'multi.title': 'Multi-Currency Converter',
    'multi.subtitle': 'Convert to multiple currencies instantly with live rates',
    'multi.from': 'From',
    'multi.to': 'To',
    'multi.amount': 'Amount',
    'multi.rates': 'Exchange Rates',
    'multi.manage': 'Manage Currencies',
    'multi.emptyState': 'Click "Add Currency" to select currencies for conversion',
    'multi.alreadyInList': 'is already in your conversion list. Please select a different currency.',
    'multi.selectCurrency': 'Select currency',
    'multi.addCurrency': '+ Add Currency',
    'multi.convertTo': 'Convert To',
    'multi.deleteAll': 'Delete All',
    'multi.titleComponent': 'Multi-Currency Converter',

    // Currency Picker & Dynamic
    'picker.selectCurrency': 'Select Currency',
    'picker.searchCurrencies': 'Search currencies',
    'picker.frequentlyUsed': '⭐ Frequently Used',
    'picker.close': 'Close',

    // Dynamic Content
    'dynamic.savedCount': '({count})',
    
    // Calculator
    'calculator.title': 'Calculator',
    'calculator.close': 'Close',
    'calculator.roundingOptions': 'Rounding Options',
    'calculator.calculationHistory': 'Calculation History',
    'calculator.clear': 'Clear',
    'calculator.noCalculations': 'No calculations yet',
    'calculator.basic': 'Basic',
    'calculator.advanced': 'Advanced',
    'calculator.history': 'History',
    'calculator.rounding': 'Rounding: {decimals}',
    'calculator.addToConverter': 'Add to Converter',
    'calculator.buttonC': 'C',
    'calculator.buttonBackspace': '⌫',
    'calculator.buttonPercent': '%',
    'calculator.buttonDivide': '÷',
    'calculator.buttonMultiply': '×',
    'calculator.buttonSubtract': '-',
    'calculator.buttonAdd': '+',
    'calculator.buttonEquals': '=',
    'calculator.buttonDecimal': '.',
    'calculator.buttonTip10': '10%',
    'calculator.buttonTip15': '15%',
    'calculator.buttonTip18': '18%',
    'calculator.buttonTip20': '20%',
    'calculator.buttonTax8': '8%',
    'calculator.buttonTax10': '10%',
    'calculator.buttonTax20': '20%',
    'calculator.buttonDiscount10': '10%',
    'calculator.buttonDiscount15': '15%',
    'calculator.buttonDiscount20': '20%',
    'calculator.buttonDiscount25': '25%',
    'calculator.advancedTools': 'Advanced tools',
    'calculator.sectionTips': 'Tips',
    'calculator.sectionTax': 'Tax',
    'calculator.sectionDiscount': 'Discounts',
    'calculator.sectionQuickMath': 'Quick math',
    'calculator.buttonSqrt': '√',
    'calculator.buttonReciprocal': '1/x',
    'calculator.buttonPlusMinus': '±',
    'calculator.splitBy2': '÷2',
    'calculator.splitBy3': '÷3',
    'calculator.splitBy4': '÷4',
    'calculator.loan': 'Loan',
    'calculator.loanTitle': 'Loan calculator',
    'calculator.loanPrincipal': 'Principal',
    'calculator.loanAnnualRate': 'Annual rate %',
    'calculator.loanTermMonths': 'Term (months)',
    'calculator.loanCalculate': 'Calculate',
    'calculator.loanTotalInterest': 'Total interest',
    'calculator.loanTotalPaid': 'Total repaid',
    'calculator.loanMonthlyPayment': 'Monthly payment',
    'calculator.loanDisplayHint': 'Enter amount, annual %, and months below',
    'calculator.loanErrPrincipal': 'Enter a valid loan amount',
    'calculator.loanErrRate': 'Enter a valid annual rate',
    'calculator.loanErrTerm': 'Enter a valid term in months',
    'calculator.loanHistoryLine': 'Loan {principal} @ {rate}% × {months} mo → {payment}/mo',
    'calculator.loanFootnote': 'Fixed-rate amortizing loan; excludes fees.',
    
    // Location
    'location.detect': 'Detect Location',
    'location.detecting': 'Detecting your location...',
    'location.permission': 'Location Permission Required',
    'location.detected': 'Location detected',
    'location.notDetected': 'Location not detected',
    
    // Footer
    'footer.copyright': '© 2025 {appTitle} - {suiteName}',
    'footer.suiteName': 'Professional Currency Converter Suite',
    'footer.terms': 'Terms of Use & Privacy',
    
    // Date/Time
    'time.lastUpdate': 'Last update',
    'time.nextUpdate': 'Next update',

    // Onboarding Guide
    'onboarding.welcome': 'Welcome to Capital!',
    'onboarding.welcomeDesc': 'Your professional currency converter with real-time rates and advanced features.',
    'onboarding.convert': 'Convert Currencies Instantly',
    'onboarding.convertDesc': 'Use the main converter to quickly convert between any currencies with live exchange rates.',
    'onboarding.multi': 'Multi-Currency View',
    'onboarding.multiDesc': 'View multiple currencies at once and compare rates across different countries.',
    'onboarding.save': 'Save Favorite Rates',
    'onboarding.saveDesc': 'Save your frequently used currency pairs for quick access and set up rate alerts.',
    'onboarding.calculator': 'Built-in Calculator',
    'onboarding.calculatorDesc': 'Use the integrated calculator for complex currency calculations and math operations.',
    'onboarding.offline': 'Offline Mode',
    'onboarding.offlineDesc': 'Works without internet using cached rates. Perfect for travel and remote areas.',
    'onboarding.alerts': 'Rate Alerts',
    'onboarding.alertsDesc': 'Get notified when your target exchange rates are reached. Never miss a good deal!',
    'onboarding.ready': 'Ready to Start!',
    'onboarding.readyDesc': 'You\'re all set! Explore the app and enjoy converting currencies with confidence.',
    'onboarding.skip': 'Skip',
    'onboarding.next': 'Next',
    'onboarding.getStarted': 'Get Started',
    
    // Authentication
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.welcome': 'Welcome',
    'auth.signout': 'Sign Out',
    'auth.orContinueWith': 'or continue with',
    'auth.continueWithEmail': 'Continue with Email',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.continueWithApple': 'Continue with Apple',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.username': 'Username',
    'auth.createAccount': 'Create Account',
    'auth.creatingAccount': 'Creating Account...',
    'auth.signingIn': 'Signing In...',
    'auth.signingOut': 'Signing Out...',
    'auth.signoutSuccess': 'You have been signed out successfully.',
    "auth.converter": "App guide",
  
  

    // Sign In Page
    'signin.welcomeBack': 'Welcome Back',
    'signin.subtitle': 'Sign in to sync your data',
    'signin.enterEmail': 'Enter your email',
    'signin.enterPassword': 'Enter your password',
    'signin.signingIn': 'Signing In...',
    'signin.signIn': 'Sign In',
    'signin.forgotPassword': 'Forgot Password?',
    'signin.orContinueWith': 'or continue with',
    'signin.continueWithGoogle': 'Continue with Google',
    'signin.continueWithApple': 'Continue with Apple',
    'signin.dontHaveAccount': "Don't have an account?",
    'signin.signUp': 'Sign Up',
    'signin.fillAllFields': 'Please fill in all fields',
    'signin.emailNotConfirmed': 'Email Not Confirmed',
    'signin.checkEmail': 'Please check your email and click the confirmation link before signing in.',
    'signin.resendConfirmation': 'Resend Confirmation Email',
    'signin.confirmationSent': 'Confirmation email sent! Please check your inbox and click the confirmation link.',
    'signin.invalidCredentials': 'Invalid Credentials',
    'signin.invalidCredentialsText': 'The email or password you entered is incorrect. Please check and try again.',
    'signin.tryAgain': 'Try Again',
    'signin.appleNotAvailable': 'Apple Sign In is only available on iOS',
    'signin.calculationResult': 'Calculation Result',
    'signin.rememberMe': 'Remember Me',

    // Sign Up Page
    'signup.createAccount': 'Create Account',
    'signup.subtitle': 'Join Capital to sync your data',
    'signup.usernameOptional': 'Username (Optional)',
    'signup.chooseUsername': 'Choose a username',
    'signup.preferredLanguage': 'Preferred Language',
    'signup.enterEmail': 'Enter your email',
    'signup.createPassword': 'Create a password',
    'signup.confirmPassword': 'Confirm your password',
    'signup.creatingAccount': 'Creating Account...',
    'signup.accountCreated': 'Account Created!',
    'signup.checkEmail': 'Please check your email and click the confirmation link to activate your account. You won\'t be able to sign in until you confirm your email.',
    'signup.verifyTitle': 'Check your email',
    'signup.verifySubtitle':
      'Enter the 6-digit code from your email, or open the confirmation link on this device, then tap Confirm.',
    'signup.codeLabel': 'Confirmation code',
    'signup.codePlaceholder': 'Code from email',
    'signup.verifyEmailButton': 'Confirm',
    'signup.verifying': 'Confirming...',
    'signup.resendCode': 'Resend code',
    'signup.resending': 'Sending...',
    'signup.resendSent': 'A new confirmation message was sent.',
    'signup.backToSignUp': 'Back to sign up',
    'signup.codeMissing': 'Please enter the confirmation code.',
    'signup.fillAllFields': 'Please fill in all fields',
    'signup.passwordsDontMatch': 'Passwords do not match',
    'signup.passwordTooShort':
      'Password must be at least {min} characters. You entered {count}.',
    'signup.passwordLengthWarning': '{count} / {min} characters',
    'signup.passwordCharUnit': 'characters',
    'signup.passwordMissingUpper': 'Include at least one uppercase letter (A–Z).',
    'signup.passwordMissingLower': 'Include at least one lowercase letter (a–z).',
    'signup.passwordMissingNumber': 'Include at least one number (0–9).',
    'signup.passwordMissingSpecial': 'Include at least one symbol (e.g. !@#$%).',
    'signup.passwordRequirements':
      'Password must be at least 8 characters and include uppercase, lowercase, a number, and a symbol (e.g. !@#$%).',
    'signup.passwordHint':
      'At least 8 characters with uppercase, lowercase, a number, and a symbol.',
    'signup.alreadyHaveAccount': 'Already have an account?',
    'signup.noVerificationEmail':
      'No confirmation email was sent. This address may already be registered — try Sign in. If your account is new, check Spam/Promotions and wait a few minutes (email sending is limited). In Supabase Dashboard: Authentication → Providers → Email → enable Confirm email.',
    'signup.verifySpamHint':
      'Also check Spam or Promotions. Delivery can take a few minutes.',
    'signup.signIn': 'Sign In',
    'signup.selectLanguage': 'Select Language',
    
    // Errors & Messages
    'error.network': 'Network error. Please check your connection.',
    'error.loading': 'Failed to load data. Please try again.',
    'error.invalidAmount': 'Please enter a valid amount',
    'error.selectCurrency': 'Please select currencies to convert',
    'error.ratesUnavailable': 'Exchange rates are currently unavailable',
    'error.duplicateCurrency': 'Duplicate Currency',
    'common.ok': 'OK',    // Chart
    'chart.title': 'Exchange Rate Chart',
    'chart.showingDataFor': 'Showing data for',
    'chart.noData': 'No chart data available',
    'chart.loading': 'Loading chart data...',
    'chart.error': 'Failed to load chart data',
    'chart.retry': 'Retry',
    'chart.currentRate': 'Current rate',
    'chart.rateChange': 'Change',
    'chart.dataPoints': 'data points',
    'chart.timePeriods.7D': '7 days',
    'chart.timePeriods.30D': '30 days',
    'chart.timePeriods.90D': '90 days',
    'chart.timePeriods.1Y': '1 year',
    'quick.action.charts': 'Charts',
    'charts.title': 'Currency rate charts',
    ...AM_FINANCE_EN,
    ...AM_FREELANCE_EN,
    ...AM_TRANSPORT_EN,
  },
  hy: {
    'app.title': 'Capital',
    'app.subtitle': 'Արժույթի գործիքներ',
    // Armenian    
    'dashboard.title': 'Վահանակ',
    'dashboard.quickActions': 'Արագ գործողություններ',
    'dashboard.reorderCards': 'Դասավորել քարտերը',
    'dashboard.reorderCardsHint':
      'Աջ մասի պատկերակից բռնեք և քաշեք քարտը։ Դասավորությունը պահվում է ավտոմատ։',
    'dashboard.finishReorder': 'Ավարտել',
    'dashboard.converter': 'Փոխարկիչ',
    'dashboard.multiCurrency': 'Բազմարժույթ',
    'dashboard.rateAlerts': 'Դրույքի ծանուցումներ',
    'dashboard.savedRates': 'Պահպանված դրույքներ',
    
    'quick.action.converter': 'Տարադրամի փոխանակում',
    'quick.action.converter.desc': 'Պրոֆեսիոնալ փոխանակում՝ լիարժեք գործառույթներով',
    'quick.action.multiCurrency': 'Բազմարժույթ փոխանակում',
    'quick.action.multiCurrency.desc': 'Արագ փոխարկում 20 արժույթով',
    'quick.action.multiCurrency.hide': 'Թաքցնել փոխանակման գործիքը',
    'quick.action.rateAlerts': 'Փոխարժեքի ծանուցումներ',
    'quick.action.rateAlerts.desc': 'Արժույթի մոնիտորինգի համար նշեք թիրախային դրույքներ',
    'quick.action.rateAlerts.hide': 'Թաքցնել ծանուցումները',
    'quick.action.savedRates': 'Պահպանված փոխարժեքներ',
    'quick.action.savedRates.desc': 'Նախընտրածների արագ հասանելիություն',
    'quick.action.savedRates.hide': 'Թաքցնել դրույքները',
    'quick.action.settings': 'Կարգավորումներ',
    'quick.action.settings.desc': 'Հաշվի և հավելվածի նախընտրություններ',
    'quick.action.calculator': 'Հաշվիչ',
    'quick.action.calculator.desc': 'Բացել բազմաֆունկցիոնալ հաշվիչը',
    'quick.action.calculator.hide': 'Թաքցնել հաշվիչը',
    'quick.action.loanCalculator': 'Վարկի հաշվիչ',
    'quick.action.vacationCalc': 'Արձակուրդային վճար',
    'quick.action.disabilityBenefit': 'Անաշխատունակության վճար',
    'quick.toolsMenu': 'Այլ գործիքներ',
    'quick.action.touristCalc': 'Տուրիստական հաշվիչ',

    'touristCalc.share.title': 'Տուրիստական հաշվիչ',
    'touristCalc.field.amount': 'Գումար (արտարժույթ)',
    'touristCalc.field.currency': 'Արժույթ',
    'touristCalc.field.rate': 'Փոխարժեք (դեպի AMD)',
    'touristCalc.rate.auto': 'Փոխարժեքը վերցվում է թարմացված տվյալներից',
    'touristCalc.rate.unavailable': 'Փոխարժեքը հասանելի չէ (թարմացրեք տվյալները)',
    'touristCalc.rate.manualToggle': 'Ձեռքով փոխարժեք',
    'touristCalc.rate.manualHint': 'Մուտքագրեք փոխարժեքը ձեռքով',
    'touristCalc.field.feePct': 'Միջնորդավճար (%)',
    'touristCalc.field.discountPct': 'Զեղչ (%)',
    'touristCalc.field.tipPct': 'Թեյավճար (%)',
    'touristCalc.result.discount': 'Զեղչ',
    'touristCalc.result.subtotal': 'Ենթագումար',
    'touristCalc.result.tip': 'Թեյավճար',
    'touristCalc.result.total': 'Ընդհանուր',
    'touristCalc.result.fee': 'Միջնորդավճար',
    'touristCalc.result.net': 'Զուտ գումար',
    'touristCalc.result.received': 'Ստացվող գումար (AMD)',
    'touristCalc.invalid': 'Անվավեր տվյալներ',
    
    'converter.title': 'Փոխարկիչ',
    'converter.subtitle': 'Պրոֆեսիոնալ փոխարկիչ՝ լիարժեք գործառույթներով',
    'converter.standard': 'Ստանդարտ',
    'converter.multiCurrency.section': 'Բազմարժույթ',    'converter.saveRate': 'Պահպանել այս դրույքը',
    'converter.disclaimer': 'Արժույթի փոխանակման պրոֆեսիոնալ լուծում՝ բարդ գործառույթներով',
    'converter.loadingRates': 'Արտարժույթի դրույքները բեռնվում են...',
    'converter.refreshData': 'Թարմացնել տվյալները',
    'converter.enterAmount': 'Ներմուծեք գումարի չափը',
    'converter.exchangeRate': 'Փոխարժեք',
    'converter.rate': 'Դրույք',
    'converter.to': 'Ուր',
    'converter.from': 'Որտեղից',
    'converter.selectCurrencies': 'Ընտրեք արժույթները՝ փոխանակումը տեսնելու համար',
    'converter.professional': 'Արժույթի պրոֆեսիոնալ փոխանակում',
    'converter.conversionResult': '{amount} {fromCurrency} = {convertedAmount} {toCurrency}',
    'converter.exchangeRateResult': '{rateLabel}: 1 {fromCurrency} = {rate} {toCurrency}',
    'converter.cbaRateNotice':
      'Պաշտոնական ՀՀ Կենտրոնական բանկի (cba.am) դրույք՝ {currencies} համար։',
    'converter.backToDashboard': '← Վերադարձ դեպի վահանակ',
    
    // Settings & Common
    'settings.title': 'Կարգավորումներ',
    'settings.subtitle': 'Կառավարեք ձեր հաշիվը և հավելվածի նախընտրությունները',
    'settings.accountInfo': 'Հաշվի տեղեկություններ',
    'settings.updateAccountInfo': 'Թարմացնել հաշվի տվյալները',
    'settings.loginRequired': 'Խնդրում ենք մուտք գործեք ձեր հաշվի տվյալները դիտելու համար',
    'settings.password': 'Գաղտնաբառ',
    'settings.changePassword': 'Փոխել գաղտնաբառը',
    'settings.newPassword': 'Նոր գաղտնաբառ',
    'settings.confirmNewPassword': 'Հաստատել նոր գաղտնաբառը',
    'settings.passwordUpdateDescription': 'Թարմացրեք գաղտնաբառը՝ ձեր հաշիվը պաշտպանելու համար',
    'settings.termsOfUse': 'Օգտագործման պայմաններ',
    'settings.privacyPolicy': 'Գաղտնիության քաղաքականություն',
    'settings.preferences': 'Նախընտրություններ',
    'settings.theme': 'Թեմա',
    'settings.system': 'Համակարգային',
    'settings.light': 'Բաց',
    'settings.dark': 'Մութ',
    'settings.language': 'Լեզու',
    'settings.languageEnglish': 'Անգլերեն',
    'settings.languageArmenian': 'Հայերեն',
    'settings.languageRussian': 'Ռուսերեն',
    'settings.notifications': 'Ծանուցումներ',
    'settings.appLock': 'Հավելվածի կողպում',
    'settings.appLockHint':
      'Երբ հավելվածը ետևի պլանում է, նորից բացելիս պահանջվում է սարքի կողպումը՝ մատնահետք, Face ID/Touch ID կամ գաղտնաբառ, ինչպես հեռախոսը բացելիս։',
    'settings.dataManagement': 'Տվյալների կառավարում',
    'settings.exchangeRateInfo': 'Տվյալներ փոխարժեքի մասին',
    'settings.aboutExchangeRates': 'Փոխարժեքի մասին',
    'settings.exchangeRateInfoDescription':
      'Փոխարժեքները թարմացվում են ժամը մեկ անգամ։ CBA-ում հրապարակված արժույթների դեպքում AMD-ի դեպքում կիրառվում է cba.am պաշտոնական դրույքը։',
    'settings.clearCache': 'Մաքրել քեշը',
    'settings.clearAllData': 'Մաքրել բոլոր տվյալները',
    'settings.aboutSupport': 'Ծանոթություն և աջակցություն',
    'settings.about': 'Ծանոթություն',
    'settings.help': 'Օգնություն',
    'settings.contactSupport': 'Կապն ու աջակցություն',
    'contactSupport.title': 'Կապ և աջակցություն',
    'contactSupport.describeIssue': 'Նկարագրեք խնդիրը',
    'contactSupport.yourEmail': 'Ձեր էլ. փոստը (ըստ ցանկության)',
    'contactSupport.sendMessage': 'Ուղարկել հաղորդագրությունը',
    'contactSupport.messageSent': 'Հաղորդագրությունը ուղարկվեց։',
    'contactSupport.sendError': 'Չհաջողվեց ուղարկել։ Կրկին փորձեք։',
    'contactSupport.emptyMessage': 'Մուտքագրեք հաղորդագրություն',
    'contactSupport.emailUnavailable': 'Այս սարքում էլ. փոստի հավելվածը հասանելի չէ',
    'contactSupport.emailPlaceholder': 'ձեր.email@օրինակ.com',
    'contactSupport.subject': 'Capital աջակցության հարց',
    'settings.dangerZone': 'Վտանգավոր գոտի',
    'settings.deleteAccount': 'Հեռացնել հաշիվը',
    'settings.deleteAccountTitle': 'Ջնջե՞լ հաշիվը',
    'settings.deleteAccountMessage':
      'Վերջին հաստատում․ հաշիվը և դրան կապված բոլոր տվյալները կջնջվեն ընդմիշտ։',
    'settings.deleteAccountConfirm': 'Ջնջել ընդմիշտ',
    'settings.deleteAccountSuccessTitle': 'Հաշիվը ջնջվեց',
    'settings.deleteAccountSuccessMessage': 'Ձեր հաշիվը և այս սարքի տվյալները հեռացվել են։',
    'settings.deleteAccountFailed':
      'Հնարավոր չեղավ ջնջել հաշիվը։ Փորձեք դուրս գալ և կրկին, կամ կապվեք աջակցության հետ։',
    'settings.dangerZoneModalIntro':
      'Հաշիվը հեռացնելիս դուք ընդմիշտ կկորցնեք մեր սերվերներում ու այս սարքում պահված ձեր անձնական տվյալները։',
    'settings.dangerZoneModalBulletServer':
      'Սերվերում՝ պահպանված փոխարժեքներ, ազդանշաններ, բազմարժույթային ու հաշվիչի պատմություն։',
    'settings.dangerZoneModalBulletDevice':
      'Սարքում՝ կարգավորումներ, սևագրեր, քեշ, վահանակի դասավորություն։',
    'settings.dangerZoneModalBulletIrreversible':
      'Գործողությունը հետ չի բերվում։ Նույն էլ. հասցեով նոր գրանցումը կլինի թարմ, դատարկ հաշիվ։',
    'settings.dangerZoneModalBulletSupport':
      'Երկմտսքնություն ունե՞ք՝ նախ դիմեք աջակցությանը։',
    'settings.dangerZoneModalClose': 'Փակել',
    'settings.dangerZoneModalContactSupport': 'Կապ աջակցության հետ',
    'settings.deleteAccountFinalGoogle':
      'Վերջին քայլ․ հաստատման համար կբացվի Google մուտքը․ նույն հաշվով մուտք գործելուց հետո հաշիվը կջնջվի։',
    'settings.deleteAccountFinalApple':
      'Վերջին քայլ․ հաստատման համար կբացվի Apple մուտքը․ նույն հաշվով մուտք գործելուց հետո հաշիվը կջնջվի։',
    'settings.deleteAccountPasswordTitle': 'Հաստատել գաղտնաբառը',
    'settings.deleteAccountPasswordSubtitle':
      'Մուտքագրեք ձեր հաշվի գաղտնաբառը՝ հաշիվը ընդմիշտ հեռացնելու համար։',
    'settings.deleteAccountPasswordPlaceholder': 'Գաղտնաբառ',
    'settings.deleteAccountPasswordEmpty': 'Մուտքագրեք գաղտնաբառը։',
    'settings.deleteAccountPasswordWrong': 'Գաղտնաբառը սխալ է։ Կրկին փորձեք։',
    'settings.deleteAccountWrongOAuthAccount':
      'Մուտք եք գործել այլ հաշվով։ Օգտագործեք նույն Google կամ Apple հաշիվը, ինչ այս հավելվածում։',
    'settings.deleteAccountUnsupportedAuth':
      'Այս մուտքի եղանակով հաշվի հեռացումը հավելվածում հնարավոր չէ։ Դիմեք աջակցությանը։',
    'settings.enableNotifications': 'Միացնել ծանուցումները',
    'settings.sound': 'Ձայն',
    'settings.vibration': 'Վիբրացիա',
    'settings.showPreview': 'Ցուցադրել նախադիտում',
    'appLock.unlockTitle': 'Բացել Capital',
    'appLock.unlockSubtitle':
      'Օգտագործեք նույն մեթոդը, ինչ սարքի էկրանը կողպելու համար՝ գաղտնաբառ, Face ID, Touch ID կամ մատնահետք։',
    'appLock.unlockButton': 'Մուտք',
    'appLock.authPrompt': 'Հաստատեք՝ Capital-ը բացելու համար',
    'appLock.notAvailable': 'Այս սարքում սիստեմային հաստատումը հասանելի չէ։',
    'appLock.notEnrolled':
      'Նախ սարքի կարգավորումներում միացրեք էկրանի կողպում, մատնահետք կամ Face ID։',
    'appLock.failed': 'Հաստատումը ձախողվեց։',
    'appLock.webUnsupported': 'Կողպումը հասանելի է միայն iOS և Android հավելվածներում։',

    'common.enabled': 'Միացված է',
    'common.disabled': 'Անջատված',
    'common.settings': 'Կարգավորումներ',
    'common.loading': 'Բեռնում...',
    'common.error': 'Սխալ',
    'common.retry': 'Կրկին փորձել',
    'common.close': 'Փակել',
    'common.share': 'Կիսվել',
    'common.save': 'Պահպանել',
    'common.cancel': 'Չեղարկել',
    'common.delete': 'Հեռացնել',
    'common.edit': 'Խմբագրել',    'common.update': 'Թարմացնել',
    'common.more': 'Ավելի',    'common.showMore': 'Ցուցադրել ավելին',
    'common.showLess': 'Ցուցադրել քիչ',
    'common.ok': 'Լավ',
    
    // Authentication
    'auth.signin': 'Մուտք գործել',
    'auth.signup': 'Գրանցվել',
    'auth.welcome': 'Բարի գալուստ',
    'auth.signout': 'Ելք գործել',
    'auth.orContinueWith': 'կամ շարունակել հետևյալով',
    'auth.continueWithEmail': 'Շարունակել էլ-փոստով',
    'auth.continueWithGoogle': 'Շարունակել Google-ով',
    'auth.continueWithApple': 'Շարունակել Apple-ով',
    'auth.alreadyHaveAccount': 'Արդեն ունե՞ք հաշիվ',
    'auth.dontHaveAccount': "Չունե՞ք հաշիվ",
    'auth.signIn': 'Մուտք գործել',
    'auth.signUp': 'Գրանցվել',
    'auth.email': 'Էլ-Հասցե',
    'auth.password': 'Գաղտնաբառ',
    'auth.confirmPassword': 'Հաստատել գաղտնաբառը',
    'auth.username': 'Օգտանուն',
    'auth.createAccount': 'Ստեղծել հաշիվ',
    'auth.creatingAccount': 'Հաշիվը ստեղծվում է...',
    'auth.signingIn': 'Մուտք է գործում...',
    'auth.signingOut': 'Ելք է գործում...',
    'auth.signoutSuccess': 'Դուք հաջողությամբ ելք գործեցիք:',
    "auth.converter": "Հավելվածի ուղեցույց",

    // Multi-Currency
    'multi.title': 'Բազմարժույթ փոխանակում',
    'multi.subtitle': 'Արագ փոխանակում բազմաթիվ արժույթներով',
    'multi.from': 'Որտեղից',
    'multi.to': 'Ուր',
    'multi.amount': 'Գումար',
    'multi.rates': 'Փոխարժեքներ',
    'multi.manage': 'Կառավարել արժույթները',
    'multi.emptyState': 'Սեղմեք "Ավելացնել արժույթ" որպեսզի ընտրեք փոխանակման համար',
    'multi.alreadyInList': 'արդեն գոյություն ունի ձեր փոխանակման ցանկում: Խնդրում ենք ընտրեք այլ արժույթ:',
    'multi.selectCurrency': 'Ընտրել արժույթ',
    'multi.addCurrency': '+ Ավելացնել',
    'multi.convertTo': 'Փոխանակել',
    'multi.deleteAll': 'Հեռացնել բոլորը',
    'multi.titleComponent': 'Բազմարժույթ փոխանակում',

    // Currency Picker & Dynamic
    'picker.selectCurrency': 'Ընտրել արժույթ',
    'picker.searchCurrencies': 'Որոնել արժույթներ',
    'picker.frequentlyUsed': '⭐ Հաճախ օգտագործվող',
    'picker.close': 'Փակել',

    // Dynamic Content
    'dynamic.savedCount': '({count})',

    // Saved Rates
    'saved.title': 'Պահպանված',
    'saved.titles': 'Պահպանված զույգեր', // Alias for compatibility
    'saved.shortTitle': 'Պահպանված', // Short version for constrained layouts
    'saved.noRates': 'Դեռ չկան պահպանված զույգեր: Փոխանակեք արժույթները և սեղմեք "Պահպանել այս դրույքը" որպեսզի ավելացնեք:',
    'saved.savedOn': 'Պահպանվել է',
    'saved.at': 'ժամը',
    'saved.rate': 'պահպանված դրույք',
    'saved.rates': 'պահպանված դրույքներ',
    'alerts.activeAlert': 'ակտիվ ծանուցում',
    'alerts.activeAlerts': 'ակտիվ ծանուցումներ',
    'saved.deleteAll': 'Հեռացնել բոլորը',
    'saved.deleteAllConfirm': 'Դուք համոզվա՞ծ եք, որ ցանկանում եք հեռացնել բոլոր պահպանված դրույքները',
    'converter.amountLabel': 'Գումար',
    'converter.enterAmountPlaceholder': 'Մուտքագրեք գումարը',
    'converter.fromLabel': 'Որտեղից',
    'converter.toLabel': 'Ուր',
    'converter.placeholderResult': 'Մուտքագրեք գումարը՝ փոխանակումը տեսնելու համար',
    'converter.recentTitle': 'Վերջին',
    'converter.saveRateButton': 'Պահպանել',
    'converter.chartButton': 'Գրաֆիկ',
    'converter.saveSuccessTitle': 'Հաջողություն',
    'converter.saveSuccessMessage': 'Դրույքը պահպանվեց ձեր հաշվում:',
    'converter.saveSuccessLocalMessage': 'Դրույքը պահպանվեց տեղայնորեն: Մուտք գործեք՝ սարքերի միջև համաժամանակեցնելու համար:',
    'converter.saveErrorTitle': 'Սխալ',
    'converter.saveErrorMessage': 'Չհաջողվեց պահպանել դրույքը: Խնդրում ենք կրկին փորձել:',
    'saved.deleteRateTitle': 'Հեռացնել դրույքը',
    'saved.deleteRateMessage': 'Վստա՞հ եք, որ ցանկանում եք հեռացնել այս պահպանված դրույքը:',
    'saved.deleteRateCancel': 'Չեղարկել',
    'saved.deleteRateConfirm': 'Հեռացնել',
    'saved.deleteSuccessTitle': 'Հաջողություն',
    'saved.deleteSuccessMessage': 'Դրույքը հաջողությամբ հեռացվեց',
    'saved.deleteFailedTitle': 'Հեռացումը ձախողվեց',
    'saved.deleteFailedMessage': 'Չհաջողվեց հեռացնել դրույքը: Խնդրում ենք կրկին փորձել կամ ստուգել ձեր ինտերնետ կապը:',
    'saved.deleteErrorTitle': 'Սխալ',
    'saved.deleteErrorMessage': 'Անակնկալ սխալ տեղի ունեցավ դրույքը հեռացնելիս:',
    'saved.deleteAllTitle': 'Հեռացնել բոլորը',
    'saved.deleteAllMessage': 'Վստա՞հ եք, որ ցանկանում եք հեռացնել բոլոր պահպանված դրույքները: Այս գործողությունը չի կարող հետարկվել:',
    'saved.deleteAllCancel': 'Չեղարկել',
    'saved.deleteAllConfirmButton': 'Հեռացնել բոլորը',
    'saved.deleteAllErrorTitle': 'Սխալ',
    'saved.deleteAllErrorMessage': 'Չհաջողվեց հեռացնել բոլոր դրույքները',
    'saved.signInPrompt': 'Մուտք գործեք՝ ձեր արժույթի դրույքները պահպանելու և սարքերի միջև համաժամանակեցնելու համար:',
    'saved.emptyState': 'Դեռևս պահպանված դրույքներ չկան: Փոխանակեք արժույթները և սեղմեք "Պահպանել այս դրույքը" որպեսզի ավելացնեք:',
    'saved.loadingText': 'Բեռնվում են պահպանված դրույքները...',
    'saved.deletingIcon': '⏳',
    'saved.deleteIcon': '',
    'saved.hideIcon': '×',    // Rate Alert Manager
    'rateAlerts.signInRequired': 'Մուտք գործեք շարունակելու համար',
    'rateAlerts.signInMessage': 'Խնդրում ենք մուտք գործել՝ արժույթի դրույքի ծանուցումներ ստեղծելու համար',
    'rateAlerts.error': 'Սխալ',
    'rateAlerts.updateFailed': 'Չհաջողվեց թարմացնել դրույքի ծանուցումը',
    'rateAlerts.createFailed': 'Չհաջողվեց ստեղծել դրույքի ծանուցում',
    'rateAlerts.success': 'Հաջողություն',
    'rateAlerts.savedSuccessfully': 'Դրույքի ծանուցումը հաջողությամբ պահպանվեց:',
    'rateAlerts.deleteTitle': 'Հեռացնել ծանուցումը',
    'rateAlerts.deleteMessage': 'Վստա՞հ եք, որ ցանկանում եք հեռացնել այս դրույքի ծանուցումը:',
    'rateAlerts.cancelButton': 'Չեղարկել',
    'rateAlerts.deleteButton': 'Հեռացնել',
    'rateAlerts.deleteFailed': 'Չհաջողվեց հեռացնել դրույքի ծանուցումը',
    'rateAlerts.updateStatusFailed': 'Չհաջողվեց թարմացնել ծանուցման կարգավիճակը',
    'rateAlerts.title': 'Փոխարժեքի ծանուցումներ',
    'rateAlerts.signInPrompt': 'Մուտք գործեք՝ արժույթի դրույքի ծանուցումներ ստեղծելու և կառավարելու համար:',
    'rateAlerts.loading': 'Բեռնում...',
    'rateAlerts.errorPrefix': 'Սխալ: {error}',
    'rateAlerts.createButton': '+ Ստեղծել ծանուցում',
    'rateAlerts.activeCount': '{count} ակտիվ ծանուցումներ',
    'rateAlerts.emptyState': 'Դեռևս ծանուցումներ չկան։ Սահմանեք ձեր առաջին թիրախը և ստացեք ծանուցումներ դրույքների փոփոխությունների մասին',
    'rateAlerts.active': 'Ակտիվ',
    'rateAlerts.target': 'Թիրախ:',
    'rateAlerts.status': 'Կարգավիճակ:',
    'rateAlerts.created': 'Ստեղծվել է:',
    'rateAlerts.edit': 'Խմբագրել',
    'rateAlerts.delete': 'Հեռացնել',
    'rateAlerts.cancel': 'Չեղարկել',
    'rateAlerts.editAlert': 'Խմբագրել ծանուցումը',
    'rateAlerts.createAlert': 'Ստեղծել ծանուցում',
    'rateAlerts.save': 'Պահպանել',
    'rateAlerts.fromCurrency': 'Որտեղից',
    'rateAlerts.toCurrency': 'Ուր',
    'rateAlerts.targetRate': 'Թիրախային դրույք (1 {fromCurrency} = X {toCurrency})',
    'rateAlerts.enterRate': '{fromCurrency} → {toCurrency} համար մուտքագրեք',
    'rateAlerts.direction': 'Ուղղություն',
    'rateAlerts.direction.above': 'վերև',
    'rateAlerts.direction.below': 'ներքև',
    'rateAlerts.activateAlert': 'Ակտիվացնել ծանուցումը',
    'rateAlerts.status.inactive': 'Ոչ ակտիվ',
    'rateAlerts.status.active': 'Ակտիվ',
    'rateAlerts.status.notified': 'ծանուցված է',
    'rateAlerts.conditionAlreadyMetTitle': 'Ծանուցման պայմանը արդեն կատարված է',
    'rateAlerts.conditionAlreadyMetMessage': '{fromCurrency} → {toCurrency} ընթացիկ փոխարժեքը {currentRate} է, որն արդեն {condition} է ձեր {targetRate} թիրախից: Ծանուցումը կմիացվի անմիջապես:',
    'rateAlerts.createAnyway': 'Ստեղծել ամեն դեպքում',
    'rateAlerts.resetTitle': 'Վերականգնել ծանուցումը',
    'rateAlerts.resetMessage': 'Ցանկանու՞մ եք վերականգնել այս ծանուցումը: Այն կկարողանա նորից միանալ, երբ պայմանը կկատարվի:',
    'rateAlerts.resetButton': 'Վերականգնել',
    'rateAlerts.resetFailed': 'Չհաջողվեց վերականգնել ծանուցումը',
    'rateAlerts.reset': 'Վերականգնել',

    // Errors & Messages
    'error.duplicateCurrency': 'Կրկնվող արժույթ',
    
    // Calculator
    'calculator.title': 'Հաշվիչ',
    'calculator.close': 'Փակել',
    'calculator.roundingOptions': 'Կլորացման տարբերակներ',
    'calculator.calculationHistory': 'Հաշվարկների պատմություն',
    'calculator.clear': 'Մաքրել',
    'calculator.noCalculations': 'Դեռևս հաշվարկներ չկան',
    'calculator.basic': 'Հիմնական',
    'calculator.advanced': 'Ընդլայնված',
    'calculator.history': 'Պատմություն',
    'calculator.rounding': 'Կլորացում: {decimals}',
    'calculator.addToConverter': 'Ավելացնել փոխարկիչին',
    'calculator.buttonC': 'C',
    'calculator.buttonBackspace': '⌫',
    'calculator.buttonPercent': '%',
    'calculator.buttonDivide': '÷',
    'calculator.buttonMultiply': '×',
    'calculator.buttonSubtract': '-',
    'calculator.buttonAdd': '+',
    'calculator.buttonEquals': '=',
    'calculator.buttonDecimal': '.',
    'calculator.buttonTip10': '10%',
    'calculator.buttonTip15': '15%',
    'calculator.buttonTip18': '18%',
    'calculator.buttonTip20': '20%',
    'calculator.buttonTax8': '8%',
    'calculator.buttonTax10': '10%',
    'calculator.buttonTax20': '20%',
    'calculator.buttonDiscount10': '10%',
    'calculator.buttonDiscount15': '15%',
    'calculator.buttonDiscount20': '20%',
    'calculator.buttonDiscount25': '25%',
    'calculator.advancedTools': 'Ընդլայնված գործիքներ',
    'calculator.sectionTips': 'Թեյավճար',
    'calculator.sectionTax': 'Հարկ',
    'calculator.sectionDiscount': 'Զեղչեր',
    'calculator.sectionQuickMath': 'Արագ մաթ.',
    'calculator.buttonSqrt': '√',
    'calculator.buttonReciprocal': '1/x',
    'calculator.buttonPlusMinus': '±',
    'calculator.splitBy2': '÷2',
    'calculator.splitBy3': '÷3',
    'calculator.splitBy4': '÷4',
    'calculator.loan': 'Վարկ',
    'calculator.loanTitle': 'Վարկի հաշվիչ',
    'calculator.loanPrincipal': 'Գումար',
    'calculator.loanAnnualRate': 'Տարեկան %',
    'calculator.loanTermMonths': 'Ժամկետ (ամիս)',
    'calculator.loanCalculate': 'Հաշվել',
    'calculator.loanTotalInterest': 'Ընդհանուր տոկոս',
    'calculator.loanTotalPaid': 'Ընդհանուր մարում',
    'calculator.loanMonthlyPayment': 'Ամսական վճար',
    'calculator.loanDisplayHint': 'Մուտքագրեք գումարը, տոկոսադրույքը և ժամկետը ամիսներով',
    'calculator.loanErrPrincipal': 'Մուտքագրեք վավեր գումար',
    'calculator.loanErrRate': 'Մուտքագրեք վավեր տարեկան տոկոս',
    'calculator.loanErrTerm': 'Մուտքագրեք վավեր ժամկետ (ամիս)',
    'calculator.loanHistoryLine': 'Վարկ {principal} @ {rate}% × {months} ամիս → {payment}/ամիս',
    'calculator.loanFootnote': 'Ֆիքսված տոկոս, անուիտետ; առանց միջնորդավճարի։',
    
    'footer.copyright': '© 2025 {appTitle} - {suiteName}',
    'footer.suiteName': 'Արժույթի մասնագիտական փոխանակում',
    'footer.terms': 'Օգտագործման պայմաններ և գաղտնիություն',
    
    // Date/Time
    'time.lastUpdate': 'Վերջին',
    'time.nextUpdate': 'Հաջորդ',

    // Onboarding Guide (օգտագործման ուղեցույց — պաշտոնական ձևակերպումներ)
    'onboarding.welcome': '«Capital» հավելված — օգտագործման ուղեցույց',
    'onboarding.welcomeDesc': 'Սույն հավելվածը նախատեսված է արտարժույթների նկատմամբ թարմացվող փոխարժեքների մատուցման, դրանց հիման վրա հաշվարկների կատարման, ինչպես նաև կապված լրացուցիչ գործառույթների (գրաֆիկներ, զբոսաշրջային հաշվիչ, պահպանված զույգեր, փոխարժեքի ծանուցումներ, Հայաստանի Հանրապետության իրավական դաշտին վերաբերող տեղեկատվական գործիքներ) ապահովման համար։',
    'onboarding.convert': 'Հիմնական փոխարկիչ',
    'onboarding.convertDesc': 'Հիմնական էկրանում ընտրեք արժույթների զույգը և գումարը՝ ստանալու համար ընթացիկ փոխարժեքը և փոխարկման արդյունքը։ Տվյալները ստացվում են երրորդ կողմի աղբյուրներից և կարող են տարբերվել բանկային կամ փոխանակման կետերի փաստացի դրույքներից․ վճարային գործառնությունների համար անհրաժեշտ է հաստատել դրույքը ձեր ֆինանսական կազմակերպությունում։',
    'onboarding.multi': 'Բազմարժույթային դիտարկում',
    'onboarding.multiDesc': 'Նույն փոխարժեքների հիման վրա կարելի է միաժամանակ ցուցադրել մեկ արժույթից մինչև մի քանի թիրախային արժույթների արժեքները՝ արագ համեմատական վերլուծության նպատակով։',
    'onboarding.save': 'Պահպանված զույգեր և ծանուցումներ',
    'onboarding.saveDesc': 'Նախընտրած արժութային զույգերը կարելի է պահպանել հավելվածում (տեղայնորեն կամ, հաշվի մուտք գործելու դեպքում, սինքրոնացման միջոցով)։ Մուտք գործած օգտագործողը կարող է սահմանել թիրախային դրույքներ և ստանալ ծանուցումներ, երբ շուկայական պայմանները համընկնեն սահմանված շեմի հետ (սահմանափակումներ կարող են կիրառվել սարքի կամ օպերացիոն համակարգի կողմից)։',
    'onboarding.calculator': 'Հաշվիչ և վարկի մոդելավորում',
    'onboarding.calculatorDesc': 'Ներկառուցված հաշվիչը նախատեսված է առօրյա թվաբանական գործողությունների, թեյավճարի, զեղչի, հարկի մոտավոր հաշվարկների, ինչպես նաև վարկի ամսական մարման մոդելավորման համար։ Արդյունքները չեն կարող համարվել ֆինանսական, հարկային կամ իրավական խորհրդատվություն․ վերջնական որոշումները կայացրեք մասնագետների հետ։',
    'onboarding.offline': 'Անցանց',
    'onboarding.offlineDesc': 'Վերջին թարմացման պահին պահված («քեշավորված») փոխարժեքները հասանելի կարող են լինել առանց ցանցային կապի, սակայն դրանք կարող են չհամընկնել ներկա շուկայական դրույքներին։ Խորհուրդ է տրվում թարմացնել տվյալները նախքան կարևոր գործարքների կամ որոշումների կայացումը։',
    'onboarding.alerts': 'Փոխարժեքի ծանուցումներ',
    'onboarding.alertsDesc': 'Ծանուցումների առաքումը կախված է սարքի, օպերացիոն համակարգի և ծանուցումների կարգավորումներից, ինչպես նաև ցանցային հասանելիությունից․ հնարավոր են ուշացումներ կամ բացակայություն տեխնիկական պատճառներով, որոնց համար մշակողը պատասխանատվություն չի կրում։',
    'onboarding.ready': 'Ավարտ',
    'onboarding.readyDesc': '«Սկսել» կոճակը սեղմելով հաստատում եք, որ ծանոթացել եք հավելվածի հիմնական գործառույթներին։ Մանրամասն իրավական կարգավորումների համար տե՛ս «Օգտագործման պայմաններ» բաժինը Կարգավորումներում։',
    'onboarding.skip': 'Բաց թողնել',
    'onboarding.next': 'Հաջորդ',
    'onboarding.getStarted': 'Սկսել',
    
    'error.network': 'Խնդիր ցանցում: Խնդրում ենք ստուգել կապը:',
    'error.loading': 'Չհաջողվեց բեռնել տվյալները: Խնդրում ենք կրկին փորձել:',
    'success.rateSaved': 'Դրույքը հաջողությամբ պահպանվեց:',

    // Chart
    'chart.title': 'Փոխարժեքի գրաֆիկ',
    'chart.showingDataFor': 'Ցուցադրվում է տվյալներ',
    'chart.noData': 'Գրաֆիկի տվյալներ չկան',
    'chart.loading': 'Բեռնվում են գրաֆիկի տվյալները...',
    'chart.error': 'Չհաջողվեց բեռնել գրաֆիկի տվյալները',
    'chart.retry': 'Կրկին փորձել',
    'chart.currentRate': 'Ընթացիկ դրույք',
    'chart.rateChange': 'Փոխվածք',
    'chart.dataPoints': 'տվյալների կետեր',
    'chart.timePeriods.7D': '7 օր',
    'chart.timePeriods.30D': '30 օր',
    'chart.timePeriods.90D': '90 օր',
    'chart.timePeriods.1Y': '1 տարի',
    'quick.action.charts': 'Գրաֆիկներ',
    'charts.title': 'Փոխարժեքի գրաֆիկներ',

    // Sign In Page
    'signin.welcomeBack': 'Բարի վերադարձ',
    'signin.subtitle': 'Մուտք գործեք՝ ձեր տվյալները համաժամանակեցնելու համար',
    'signin.enterEmail': 'Մուտքագրեք ձեր էլ-փոստը',
    'signin.enterPassword': 'Մուտքագրեք ձեր գաղտնաբառը',
    'signin.signingIn': 'Մուտք է գործում...',
    'signin.signIn': 'Մուտք գործել',
    'signin.forgotPassword': 'Մոռացել եք գաղտնաբառը?',
    'signin.orContinueWith': 'կամ շարունակել հետևյալով',
    'signin.continueWithGoogle': 'Շարունակել Google-ով',
    'signin.continueWithApple': 'Շարունակել Apple-ով',
    'signin.dontHaveAccount': "Հաշիվ չունե՞ք",
    'signin.signUp': 'Գրանցվել',
    'signin.fillAllFields': 'Խնդրում ենք լրացնել բոլոր դաշտերը',
    'signin.emailNotConfirmed': 'Էլ-փոստը հաստատված չէ',
    'signin.checkEmail': 'Խնդրում ենք ստուգել ձեր էլ-փոստը և մուտք գործելուց առաջ սեղմել հաստատման հղումը:',
    'signin.resendConfirmation': 'Վերաուղարկել հաստատման նամակ',
    'signin.confirmationSent': 'Հաստատման նամակը ուղարկվեց: Խնդրում ենք ստուգել ձեր փոստարկղը և սեղմել հաստատման հղումը:',
    'signin.invalidCredentials': 'Անվավեր հավատարմագրություններ',
    'signin.invalidCredentialsText': 'Մուտքագրված էլ-փոստը կամ գաղտնաբառը սխալ է: Խնդրում ենք ստուգել և կրկին փորձել:',
    'signin.tryAgain': 'Կրկին փորձել',
    'signin.appleNotAvailable': 'Apple մուտքը հասանելի է միայն iOS-ի համար',
    'signin.calculationResult': 'Հաշվարկի արդյունք',
    'signin.rememberMe': 'Հիշել ինձ',

    // Sign Up Page
    'signup.createAccount': 'Ստեղծել հաշիվ',
    'signup.subtitle': 'Միացեք Capital-ին՝ ձեր տվյալները համաժամանակեցնելու համար',
    'signup.usernameOptional': 'Օգտանուն (ըստ ցանկության)',
    'signup.chooseUsername': 'Ընտրեք օգտանուն',
    'signup.preferredLanguage': 'Նախընտրած լեզու',
    'signup.enterEmail': 'Մուտքագրեք ձեր էլ-փոստը',
    'signup.createPassword': 'Ստեղծեք գաղտնաբառ',
    'signup.confirmPassword': 'Հաստատեք ձեր գաղտնաբառը',
    'signup.creatingAccount': 'Հաշիվը ստեղծվում է...',
    'signup.accountCreated': 'Հաշիվը ստեղծվեց:',
    'signup.checkEmail': 'Խնդրում ենք ստուգել ձեր էլ-փոստը և սեղմել հաստատման հղումը՝ ձեր հաշիվը ակտիվացնելու համար: Դուք չեք կարող մուտք գործել մինչև էլ-փոստը հաստատելը:',
    'signup.verifyTitle': 'Ստուգեք էլ-փոստը',
    'signup.verifySubtitle':
      'Մուտքագրեք նամակի 6 նիշ կոդը, կամ այս սարքում բացեք հաստատման հղումը, ապա սեղմեք «Հաստատել»:',
    'signup.codeLabel': 'Հաստատման կոդ',
    'signup.codePlaceholder': 'Կոդը նամակից',
    'signup.verifyEmailButton': 'Հաստատել',
    'signup.verifying': 'Հաստատվում է...',
    'signup.resendCode': 'Կրկին ուղարկել կոդը',
    'signup.resending': 'Ուղարկվում է...',
    'signup.resendSent': 'Նոր հաստատման հաղորդագրություն է ուղարկվել:',
    'signup.backToSignUp': 'Վերադառնալ գրանցմանը',
    'signup.codeMissing': 'Խնդրում ենք մուտքագրել հաստատման կոդը:',
    'signup.fillAllFields': 'Խնդրում ենք լրացնել բոլոր դաշտերը',
    'signup.passwordsDontMatch': 'Գաղտնաբառերը չեն համապատասխանում',
    'signup.passwordTooShort':
      'Գաղտնաբառը պետք է լինի առնվազն {min} նիշ։ Դուք մուտքագրել եք {count}։',
    'signup.passwordLengthWarning': '{count} / {min} նիշ',
    'signup.passwordCharUnit': 'նիշ',
    'signup.passwordMissingUpper': 'Ավելացրեք գոնե մեկ մեծատառ (A–Z)։',
    'signup.passwordMissingLower': 'Ավելացրեք գոնե մեկ փոքրատառ (a–z)։',
    'signup.passwordMissingNumber': 'Ավելացրեք գոնե մեկ թիվ (0–9)։',
    'signup.passwordMissingSpecial': 'Ավելացրեք գոնե մեկ նշան (օր. !@#$%)։',
    'signup.passwordRequirements':
      'Գաղտնաբառը պետք է լինի առնվազն 8 նիշ և պարունակի մեծատառ, փոքրատառ, թիվ և նշան (օր. !@#$%)։',
    'signup.passwordHint':
      'Առնվազն 8 նիշ՝ մեծատառ, փոքրատառ, թիվ և նշան։',
    'signup.alreadyHaveAccount': 'Արդեն ունե՞ք հաշիվ',
    'signup.noVerificationEmail':
      'Հաստատման նամակ չի ուղարկվել: Այս էլ. հասցեն հնարավոր է արդեն գրանցված լինի՝ փորձեք «Մուտք գործել»: Եթե հաշիվը նոր է, ստուգեք Spam/Գովազդային թղթապանակը և սպասեք մի քանի րոպե (նամակների ուղարկումը սահմանափակ է): Supabase Dashboard → Authentication → Providers → Email → միացրեք Confirm email:',
    'signup.verifySpamHint':
      'Ստուգեք նաև Spam կամ Գովազդային: Նամակը կարող է ուշանալ մի քանի րոպե:',
    'signup.signIn': 'Մուտք գործել',
    'signup.selectLanguage': 'Ընտրել լեզու',
    ...AM_FINANCE_HY,
    ...AM_FREELANCE_HY,
    ...AM_TRANSPORT_HY,
  },
  ru: {
    'app.title': 'Capital',
    'app.subtitle': 'Курсы и конвертация',
    // Russian    
    'dashboard.title': 'Панель',
    'dashboard.quickActions': 'Быстрые действия',
    'dashboard.reorderCards': 'Порядок карточек',
    'dashboard.reorderCardsHint':
      'Перетащите значок справа, чтобы переместить плитку. Порядок сохраняется автоматически.',
    'dashboard.finishReorder': 'Готово',
    'dashboard.converter': 'Конвертер',
    'dashboard.multiCurrency': 'Мультивалютный',
    'dashboard.rateAlerts': 'Уведомления о курсах',
    'dashboard.savedRates': 'Сохраненные курсы',
    
    // Compact versions for header buttons    
    'quick.action.converter': 'Конвертер валют',
    'quick.action.converter.desc': 'Профессиональный конвертер со всеми функциями',
    'quick.action.multiCurrency': 'Мультивалютный',
    'quick.action.multiCurrency.desc': 'Быстрая конвертация в 20 валют',
    'quick.action.multiCurrency.hide': 'Скрыть инструмент конвертации',
    'quick.action.rateAlerts': 'Уведомления о курсах',
    'quick.action.rateAlerts.desc': 'Установите целевые курсы для мониторинга валют',
    'quick.action.rateAlerts.hide': 'Скрыть уведомления',
    'quick.action.savedRates': 'Сохраненные курсы',
    'quick.action.savedRates.desc': 'Быстрый доступ к избранному',
    'quick.action.savedRates.hide': 'Скрыть сохраненные курсы',
    'quick.action.settings': 'Настройки',
    'quick.action.settings.desc': 'Учетная запись и настройки приложения',
    'quick.action.calculator': 'Быстрый калькулятор',
    'quick.action.calculator.desc': 'Открыть базовый математический калькулятор',
    'quick.action.calculator.hide': 'Скрыть виджет калькулятора',
    'quick.action.loanCalculator': 'Кредитный калькулятор',
    'quick.action.vacationCalc': 'Отпускные',
    'quick.action.disabilityBenefit': 'Пособие по нетрудоспособности',
    'quick.toolsMenu': 'Другие инструменты',
    'quick.action.touristCalc': 'Туристический калькулятор',

    'touristCalc.share.title': 'Туристический калькулятор',
    'touristCalc.field.amount': 'Сумма (иностранная валюта)',
    'touristCalc.field.currency': 'Валюта',
    'touristCalc.field.rate': 'Курс (к AMD)',
    'touristCalc.rate.auto': 'Курс берётся из обновлённых данных',
    'touristCalc.rate.unavailable': 'Курс недоступен (обновите данные)',
    'touristCalc.rate.manualToggle': 'Ручной курс',
    'touristCalc.rate.manualHint': 'Введите курс вручную',
    'touristCalc.field.feePct': 'Комиссия (%)',
    'touristCalc.field.discountPct': 'Скидка (%)',
    'touristCalc.field.tipPct': 'Чаевые (%)',
    'touristCalc.result.discount': 'Скидка',
    'touristCalc.result.subtotal': 'Промежуточный итог',
    'touristCalc.result.tip': 'Чаевые',
    'touristCalc.result.total': 'Итого',
    'touristCalc.result.fee': 'Комиссия',
    'touristCalc.result.net': 'Чистая сумма',
    'touristCalc.result.received': 'Сумма к получению (AMD)',
    'touristCalc.invalid': 'Некорректные данные',

    'converter.title': 'Конвертер валют',
    'converter.subtitle': 'Полный набор конвертации валют с расширенными функциями',
    'converter.standard': 'Стандартная конвертация',
    'converter.multiCurrency.section': 'Мультивалютный конвертер',    'converter.saveRate': 'Сохранить этот курс',
    'converter.disclaimer': 'Профессиональный конвертер валют с курсами в реальном времени и расширенными функциями',
    'converter.loadingRates': 'Загрузка курсов валют...',
    'converter.refreshData': 'Обновить данные',
    'converter.enterAmount': 'Введите сумму для конвертации',
    'converter.exchangeRate': 'Обменный курс',
    'converter.rate': 'Курс',
    'converter.to': 'В',
    'converter.from': 'Из',
    'converter.selectCurrencies': 'Выберите валюты для просмотра конвертации',
    'converter.professional': 'Профессиональный конвертер валют с курсами в реальном времени и расширенными функциями',
    'converter.conversionResult': '{amount} {fromCurrency} = {convertedAmount} {toCurrency}',
    'converter.exchangeRateResult': '{rateLabel}: 1 {fromCurrency} = {rate} {toCurrency}',
    'converter.cbaRateNotice':
      'Официальный курс Центрального банка Армении (cba.am) для {currencies}.',
    'converter.backToDashboard': '← Назад к панели',
    'converter.amountLabel': 'Сумма',
    'converter.enterAmountPlaceholder': 'Введите сумму',
    'converter.placeholderResult': 'Введите сумму, чтобы увидеть конвертацию',
    'converter.recentTitle': 'Недавние',
    'converter.saveRateButton': 'Сохранить',
    'converter.chartButton': 'График',
    'converter.saveSuccessTitle': 'Готово',
    'converter.saveSuccessMessage': 'Курс сохранён в вашем аккаунте!',
    'converter.saveSuccessLocalMessage':
      'Курс сохранён локально. Войдите, чтобы синхронизировать между устройствами.',
    'converter.saveErrorTitle': 'Ошибка',
    'converter.saveErrorMessage': 'Не удалось сохранить курс. Попробуйте снова.',

    // Settings & Common
    'settings.title': 'Настройки',
    'settings.subtitle': 'Управляйте своей учетной записью и настройками приложения',
    'settings.accountInfo': 'Информация об аккаунте',
    'settings.updateAccountInfo': 'Обновить информацию об аккаунте',
    'settings.loginRequired': 'Пожалуйста, войдите в систему, чтобы просмотреть информацию об аккаунте',
    'settings.password': 'Пароль',
    'settings.changePassword': 'Изменить пароль',
    'settings.newPassword': 'Новый пароль',
    'settings.confirmNewPassword': 'Подтвердить новый пароль',
    'settings.passwordUpdateDescription': 'Обновите свой пароль, чтобы обеспечить безопасность аккаунта',
    'settings.termsOfUse': 'Условия использования',
    'settings.privacyPolicy': 'Политика конфиденциальности',
    'settings.preferences': 'Предпочтения',
    'settings.theme': 'Тема',
    'settings.system': 'Системная',
    'settings.light': 'Светлая',
    'settings.dark': 'Темная',
    'settings.language': 'Язык',
    'settings.languageEnglish': 'Английский',
    'settings.languageArmenian': 'Армянский',
    'settings.languageRussian': 'Русский',
    'settings.notifications': 'Уведомления',
    'settings.appLock': 'Блокировка приложения',
    'settings.appLockHint':
      'После сворачивания для входа потребуется код или биометрия — как при разблокировке телефона.',
    'settings.dataManagement': 'Управление данными',
    'settings.exchangeRateInfo': 'Информация о курсах',
    'settings.aboutExchangeRates': 'О курсах',
    'settings.exchangeRateInfoDescription':
      'Курсы обновляются каждый час. Для валют, публикуемых ЦБ Армении, к парам с AMD применяется официальный курс cba.am.',
    'settings.clearCache': 'Очистить кеш',
    'settings.clearAllData': 'Очистить все данные',
    'settings.aboutSupport': 'О программе и поддержка',
    'settings.about': 'О программе',
    'settings.help': 'Справка',
    'settings.contactSupport': 'Связь с поддержкой',
    'contactSupport.title': 'Связь и поддержка',
    'contactSupport.describeIssue': 'Опишите проблему',
    'contactSupport.yourEmail': 'Ваш email (необязательно)',
    'contactSupport.sendMessage': 'Отправить сообщение',
    'contactSupport.messageSent': 'Сообщение отправлено.',
    'contactSupport.sendError': 'Не удалось отправить. Попробуйте снова.',
    'contactSupport.emptyMessage': 'Введите сообщение',
    'contactSupport.emailUnavailable': 'На этом устройстве почта недоступна',
    'contactSupport.emailPlaceholder': 'ваш.email@example.com',
    'contactSupport.subject': 'Запрос в поддержку Capital',
    'settings.dangerZone': 'Опасная зона',
    'settings.deleteAccount': 'Удалить аккаунт',
    'settings.deleteAccountTitle': 'Удалить аккаунт?',
    'settings.deleteAccountMessage':
      'Последнее подтверждение: аккаунт и все связанные данные будут удалены навсегда.',
    'settings.deleteAccountConfirm': 'Удалить навсегда',
    'settings.deleteAccountSuccessTitle': 'Аккаунт удалён',
    'settings.deleteAccountSuccessMessage': 'Аккаунт и данные на этом устройстве удалены.',
    'settings.deleteAccountFailed':
      'Не удалось удалить аккаунт. Выйдите и попробуйте снова или обратитесь в поддержку.',
    'settings.dangerZoneModalIntro':
      'Удаление аккаунта навсегда стирает все ваши персональные данные на серверах и на этом устройстве.',
    'settings.dangerZoneModalBulletServer':
      'В облаке: сохранённые курсы, оповещения, история конвертера и калькулятора.',
    'settings.dangerZoneModalBulletDevice':
      'На устройстве: настройки, черновики, кэш, порядок виджетов и прочие локальные данные.',
    'settings.dangerZoneModalBulletIrreversible':
      'Отменить нельзя. Тот же email можно использовать снова — это будет новый пустой аккаунт.',
    'settings.dangerZoneModalBulletSupport':
      'Сомневаетесь? Сначала напишите в поддержку.',
    'settings.dangerZoneModalClose': 'Закрыть',
    'settings.dangerZoneModalContactSupport': 'Связаться с поддержкой',
    'settings.deleteAccountFinalGoogle':
      'Последний шаг: войдите снова через Google, чтобы подтвердить личность, затем аккаунт будет удалён.',
    'settings.deleteAccountFinalApple':
      'Последний шаг: войдите снова через Apple, чтобы подтвердить личность, затем аккаунт будет удалён.',
    'settings.deleteAccountPasswordTitle': 'Подтвердите пароль',
    'settings.deleteAccountPasswordSubtitle':
      'Введите пароль учётной записи для окончательного удаления.',
    'settings.deleteAccountPasswordPlaceholder': 'Пароль',
    'settings.deleteAccountPasswordEmpty': 'Введите пароль.',
    'settings.deleteAccountPasswordWrong': 'Неверный пароль. Попробуйте снова.',
    'settings.deleteAccountWrongOAuthAccount':
      'Вы вошли другим аккаунтом. Используйте тот же Google или Apple, что и в приложении.',
    'settings.deleteAccountUnsupportedAuth':
      'Этот способ входа не позволяет удалить аккаунт в приложении. Обратитесь в поддержку.',
    'settings.enableNotifications': 'Включить уведомления',
    'settings.sound': 'Звук',
    'settings.vibration': 'Вибрация',
    'settings.showPreview': 'Показать превью',
    'appLock.unlockTitle': 'Разблокируйте Capital',
    'appLock.unlockSubtitle':
      'Используйте тот же способ, что для разблокировки устройства: PIN, отпечаток или Face ID.',
    'appLock.unlockButton': 'Разблокировать',
    'appLock.authPrompt': 'Подтвердите для входа в Capital',
    'appLock.notAvailable': 'Вход по настройкам устройства недоступен.',
    'appLock.notEnrolled': 'Сначала включите блокировку экрана или биометрию в настройках телефона.',
    'appLock.failed': 'Подтверждение не выполнено.',
    'appLock.webUnsupported': 'Доступно только в приложениях для iOS и Android.',

    'common.enabled': 'Включено',
    'common.disabled': 'Отключено',
    'common.settings': 'Настройки',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.retry': 'Повторить',
    'common.close': 'Закрыть',
    'common.share': 'Поделиться',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',    'common.update': 'Обновить',
    'common.more': 'Больше',    'common.showMore': 'Показать больше',
    'common.showLess': 'Показать меньше',
    'common.ok': 'OK',

    // Multi-Currency
    'multi.title': 'Мультивалютный конвертер',
    'multi.subtitle': 'Быстрая конвертация в несколько валют с курсами в реальном времени',
    'multi.from': 'Из',
    'multi.to': 'В',
    'multi.amount': 'Сумма',
    'multi.rates': 'Обменные курсы',
    'multi.manage': 'Управление валютами',
    'multi.emptyState': 'Нажмите "Добавить валюту" для выбора валют для конвертации',
    'multi.alreadyInList': 'уже есть в вашем списке конвертации. Пожалуйста, выберите другую валюту.',
    'multi.selectCurrency': 'Выберите валюту',
    'multi.addCurrency': '+ Добавить',
    'multi.convertTo': 'Конвертировать в',
    'multi.deleteAll': 'Удалить все',
    'multi.titleComponent': 'Мультивалютный конвертер',

    // Currency Picker & Dynamic
    'picker.selectCurrency': 'Выберите валюту',
    'picker.searchCurrencies': 'Поиск валют',
    'picker.frequentlyUsed': '⭐ Часто используемые',
    'picker.close': 'Закрыть',

    // Dynamic Content
    'dynamic.savedCount': '({count})',

    // Saved Rates
    'saved.title': 'Сохраненные курсы',
    'saved.titles': 'Сохраненные курсы', // Alias for compatibility
    'saved.shortTitle': 'Сохраненные', // Short version for constrained layouts
    'saved.noRates': 'Пока нет сохраненных курсов. Конвертируйте валюты и нажмите "Сохранить этот курс", чтобы добавить!',
    'saved.savedOn': 'Сохранено',
    'saved.at': 'в',
    'saved.rate': 'сохраненный курс',
    'saved.rates': 'сохраненные курсы',
    'alerts.activeAlert': 'активное уведомление',
    'alerts.activeAlerts': 'активные уведомления',
    'saved.deleteAll': 'Удалить все',
    'saved.deleteAllConfirm': 'Вы уверены, что хотите удалить все сохраненные курсы?',
    'converter.fromLabel': 'Из',
    'converter.toLabel': 'В',
    'saved.deleteRateTitle': 'Удалить курс',
    'saved.deleteRateMessage': 'Удалить этот сохранённый курс?',
    'saved.deleteRateCancel': 'Отмена',
    'saved.deleteRateConfirm': 'Удалить',
    'saved.deleteSuccessTitle': 'Готово',
    'saved.deleteSuccessMessage': 'Курс успешно удалён',
    'saved.deleteFailedTitle': 'Не удалось удалить',
    'saved.deleteFailedMessage':
      'Не удалось удалить курс. Проверьте подключение и попробуйте снова.',
    'saved.deleteErrorTitle': 'Ошибка',
    'saved.deleteErrorMessage': 'Произошла непредвиденная ошибка при удалении курса.',
    'saved.deleteAllTitle': 'Удалить все',
    'saved.deleteAllMessage':
      'Удалить все сохранённые курсы? Это действие нельзя отменить.',
    'saved.deleteAllCancel': 'Отмена',
    'saved.deleteAllConfirmButton': 'Удалить все',
    'saved.deleteAllErrorTitle': 'Ошибка',
    'saved.deleteAllErrorMessage': 'Не удалось удалить все курсы',
    'saved.signInPrompt':
      'Войдите, чтобы сохранять курсы и синхронизировать их между устройствами.',
    'saved.emptyState':
      'Сохранённых курсов пока нет. Конвертируйте валюты и нажмите «Сохранить этот курс».',
    'saved.loadingText': 'Загрузка сохранённых курсов...',
    'saved.deletingIcon': '⏳',
    'saved.deleteIcon': '',
    'saved.hideIcon': '×',

    // Errors & Messages
    'error.duplicateCurrency': 'Дубликат валюты',
    
    // Calculator
    'calculator.title': 'Калькулятор',
    'calculator.close': 'Закрыть',
    'calculator.roundingOptions': 'Опции округления',
    'calculator.calculationHistory': 'История вычислений',
    'calculator.clear': 'Очистить',
    'calculator.noCalculations': 'Пока нет вычислений',
    'calculator.basic': 'Базовый',
    'calculator.advanced': 'Расширенный',
    'calculator.history': 'История',
    'calculator.rounding': 'Округление: {decimals}',
    'calculator.addToConverter': 'Добавить в конвертер',
    'calculator.buttonC': 'C',
    'calculator.buttonBackspace': '⌫',
    'calculator.buttonPercent': '%',
    'calculator.buttonDivide': '÷',
    'calculator.buttonMultiply': '×',
    'calculator.buttonSubtract': '-',
    'calculator.buttonAdd': '+',
    'calculator.buttonEquals': '=',
    'calculator.buttonDecimal': '.',
    'calculator.buttonTip10': '10%',
    'calculator.buttonTip15': '15%',
    'calculator.buttonTip18': '18%',
    'calculator.buttonTip20': '20%',
    'calculator.buttonTax8': '8%',
    'calculator.buttonTax10': '10%',
    'calculator.buttonTax20': '20%',
    'calculator.buttonDiscount10': '10%',
    'calculator.buttonDiscount15': '15%',
    'calculator.buttonDiscount20': '20%',
    'calculator.buttonDiscount25': '25%',
    'calculator.advancedTools': 'Расширенные инструменты',
    'calculator.sectionTips': 'Чаевые',
    'calculator.sectionTax': 'Налог',
    'calculator.sectionDiscount': 'Скидки',
    'calculator.sectionQuickMath': 'Быстрая мат.',
    'calculator.buttonSqrt': '√',
    'calculator.buttonReciprocal': '1/x',
    'calculator.buttonPlusMinus': '±',
    'calculator.splitBy2': '÷2',
    'calculator.splitBy3': '÷3',
    'calculator.splitBy4': '÷4',
    'calculator.loan': 'Кредит',
    'calculator.loanTitle': 'Кредитный калькулятор',
    'calculator.loanPrincipal': 'Сумма',
    'calculator.loanAnnualRate': 'Годовая ставка %',
    'calculator.loanTermMonths': 'Срок (мес.)',
    'calculator.loanCalculate': 'Рассчитать',
    'calculator.loanTotalInterest': 'Всего процентов',
    'calculator.loanTotalPaid': 'Всего к выплате',
    'calculator.loanMonthlyPayment': 'Ежемесячный платёж',
    'calculator.loanDisplayHint': 'Введите сумму, % и срок в месяцах',
    'calculator.loanErrPrincipal': 'Введите корректную сумму',
    'calculator.loanErrRate': 'Введите корректную ставку',
    'calculator.loanErrTerm': 'Введите срок в месяцах',
    'calculator.loanHistoryLine': 'Кредит {principal} @ {rate}% × {months} мес → {payment}/мес',
    'calculator.loanFootnote': 'Аннуитет, фиксированная ставка; без учёта комиссий.',
    
    'footer.copyright': '© 2025 {appTitle} - {suiteName}',
    'footer.suiteName': 'Профессиональный набор конвертеров валют',
    'footer.terms': 'Условия использования и конфиденциальность',
    
    // Date/Time
    'time.lastUpdate': 'Последнее',
    'time.nextUpdate': 'Следующее',

    // Onboarding Guide
    'onboarding.welcome': 'Добро пожаловать в Capital!',
    'onboarding.welcomeDesc': 'Ваш профессиональный конвертер валют с курсами в реальном времени и расширенными функциями.',
    'onboarding.convert': 'Конвертируйте валюты мгновенно',
    'onboarding.convertDesc': 'Используйте основной конвертер для быстрого конвертирования между любыми валютами с курсами в реальном времени.',
    'onboarding.multi': 'Мультивалютный вид',
    'onboarding.multiDesc': 'Просматривайте несколько валют одновременно и сравнивайте курсы в разных странах.',
    'onboarding.save': 'Сохраняйте любимые курсы',
    'onboarding.saveDesc': 'Сохраняйте часто используемые пары валют для быстрого доступа и настройте оповещения о курсах.',
    'onboarding.calculator': 'Встроенный калькулятор',
    'onboarding.calculatorDesc': 'Используйте интегрированный калькулятор для сложных валютных расчетов и математических операций.',
    'onboarding.offline': 'Автономный режим',
    'onboarding.offlineDesc': 'Работает без интернета, используя кэшированные курсы. Идеально для путешествий и удаленных мест.',
    'onboarding.alerts': 'Оповещения о курсах',
    'onboarding.alertsDesc': 'Получайте уведомления, когда достигаются ваши целевые обменные курсы. Никогда не упускайте выгодную сделку!',
    'onboarding.ready': 'Готовы начать!',
    'onboarding.readyDesc': 'Вы готовы! Исследуйте приложение и наслаждайтесь конвертацией валют с уверенностью.',
    'onboarding.skip': 'Пропустить',
    'onboarding.next': 'Далее',
    'onboarding.getStarted': 'Начать',

     // Chart
    'chart.title': 'График обменного курса',
    'chart.showingDataFor': 'Показ данных',
    'chart.noData': 'Данные диаграммы отсутствуют.',
    'chart.loading': 'Загрузка графических данных...',
    'chart.error': 'Невозможно загрузить графические данные.',
    'chart.retry': 'Попробуйте еще раз',
    'chart.currentRate': 'Текущая ставка',
    'chart.rateChange': 'Измененный',
    'chart.dataPoints': 'точки данных',
    'chart.timePeriods.7D': '7 дней',
    'chart.timePeriods.30D': '30 дней',
    'chart.timePeriods.90D': '90 дней',
    'chart.timePeriods.1Y': '1 год',
    'quick.action.charts': 'Графики',
    'charts.title': 'Графики обменных курсов',
    
    // Authentication
    'auth.signin': 'Войти',
    'auth.signup': 'Зарегистрироваться',
    'auth.welcome': 'Добро пожаловать',
    'auth.signout': 'Выйти',
    'auth.orContinueWith': 'или продолжить с',
    'auth.continueWithEmail': 'Продолжить с email',
    'auth.continueWithGoogle': 'Продолжить с Google',
    'auth.continueWithApple': 'Продолжить с Apple',
    'auth.alreadyHaveAccount': 'Уже есть аккаунт?',
    'auth.dontHaveAccount': "Нет аккаунта?",
    'auth.signIn': 'Войти',
    'auth.signUp': 'Зарегистрироваться',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.confirmPassword': 'Подтвердить пароль',
    'auth.username': 'Имя пользователя',
    'auth.createAccount': 'Создать аккаунт',
    'auth.creatingAccount': 'Создаю аккаунт...',
    'auth.signingIn': 'Вхожу...',
    'auth.signingOut': 'Выхожу...',
    'auth.signoutSuccess': 'Вы успешно вышли!',
    "auth.converter": "Руководство по приложению",
    
    'error.network': 'Ошибка сети. Проверьте подключение.',
    'error.loading': 'Не удалось загрузить данные. Попробуйте снова.',
    'success.rateSaved': 'Курс успешно сохранен!',

    // Sign In Page
    'signin.welcomeBack': 'Добро пожаловать обратно',
    'signin.subtitle': 'Войдите, чтобы синхронизировать свои данные',
    'signin.enterEmail': 'Введите ваш email',
    'signin.enterPassword': 'Введите ваш пароль',
    'signin.signingIn': 'Вход...',
    'signin.signIn': 'Войти',
    'signin.forgotPassword': 'Забыли пароль?',
    'signin.orContinueWith': 'или продолжить с',
    'signin.continueWithGoogle': 'Продолжить с Google',
    'signin.continueWithApple': 'Продолжить с Apple',
    'signin.dontHaveAccount': "Нет аккаунта?",
    'signin.signUp': 'Зарегистрироваться',
    'signin.fillAllFields': 'Пожалуйста, заполните все поля',
    'signin.emailNotConfirmed': 'Email не подтвержден',
    'signin.checkEmail': 'Пожалуйста, проверьте ваш email и нажмите ссылку подтверждения перед входом.',
    'signin.resendConfirmation': 'Отправить письмо подтверждения повторно',
    'signin.confirmationSent': 'Письмо подтверждения отправлено! Проверьте ваш почтовый ящик и нажмите ссылку подтверждения.',
    'signin.invalidCredentials': 'Неверные учетные данные',
    'signin.invalidCredentialsText': 'Введенный email или пароль неверны. Пожалуйста, проверьте и попробуйте снова.',
    'signin.tryAgain': 'Попробовать снова',
    'signin.appleNotAvailable': 'Вход через Apple доступен только на iOS',
    'signin.calculationResult': 'Результат вычисления',
    'signin.rememberMe': 'Запомнить меня',

    // Sign Up Page
    'signup.createAccount': 'Создать аккаунт',
    'signup.subtitle': 'Присоединяйтесь к Capital для синхронизации данных',
    'signup.usernameOptional': 'Имя пользователя (необязательно)',
    'signup.chooseUsername': 'Выберите имя пользователя',
    'signup.preferredLanguage': 'Предпочитаемый язык',
    'signup.enterEmail': 'Введите ваш email',
    'signup.createPassword': 'Создайте пароль',
    'signup.confirmPassword': 'Подтвердите ваш пароль',
    'signup.creatingAccount': 'Создание аккаунта...',
    'signup.accountCreated': 'Аккаунт создан!',
    'signup.checkEmail': 'Пожалуйста, проверьте ваш email и нажмите ссылку подтверждения для активации аккаунта. Вы не сможете войти, пока не подтвердите email.',
    'signup.verifyTitle': 'Проверьте почту',
    'signup.verifySubtitle':
      'Введите 6-значный код из письма или откройте ссылку подтверждения на этом устройстве, затем нажмите Подтвердить.',
    'signup.codeLabel': 'Код подтверждения',
    'signup.codePlaceholder': 'Код из письма',
    'signup.verifyEmailButton': 'Подтвердить',
    'signup.verifying': 'Подтверждение...',
    'signup.resendCode': 'Отправить код снова',
    'signup.resending': 'Отправка...',
    'signup.resendSent': 'Отправлено новое письмо с подтверждением.',
    'signup.backToSignUp': 'Назад к регистрации',
    'signup.codeMissing': 'Введите код подтверждения.',
    'signup.fillAllFields': 'Пожалуйста, заполните все поля',
    'signup.passwordsDontMatch': 'Пароли не совпадают',
    'signup.passwordTooShort':
      'Пароль должен быть не короче {min} символов. Вы ввели {count}.',
    'signup.passwordLengthWarning': '{count} / {min} симв.',
    'signup.passwordCharUnit': 'симв.',
    'signup.passwordMissingUpper': 'Добавьте хотя бы одну заглавную букву (A–Z).',
    'signup.passwordMissingLower': 'Добавьте хотя бы одну строчную букву (a–z).',
    'signup.passwordMissingNumber': 'Добавьте хотя бы одну цифру (0–9).',
    'signup.passwordMissingSpecial': 'Добавьте хотя бы один символ (напр. !@#$%).',
    'signup.passwordRequirements':
      'Пароль должен быть не короче 8 символов и содержать заглавную и строчную буквы, цифру и символ (например !@#$%).',
    'signup.passwordHint':
      'Минимум 8 символов: заглавная, строчная, цифра и символ.',
    'signup.alreadyHaveAccount': 'Уже есть аккаунт?',
    'signup.noVerificationEmail':
      'Письмо с подтверждением не отправлено. Возможно, этот email уже зарегистрирован — попробуйте войти. Если аккаунт новый, проверьте Спам и подождите несколько минут (лимит писем). В Supabase: Authentication → Providers → Email → включите подтверждение email.',
    'signup.verifySpamHint':
      'Проверьте папку «Спам» или «Промоакции». Письмо может прийти с задержкой.',
    'signup.signIn': 'Войти',
    'signup.selectLanguage': 'Выбрать язык',

    // Rate Alert Manager
    'rateAlerts.signInRequired': 'Требуется вход',
    'rateAlerts.signInMessage': 'Пожалуйста, войдите в систему, чтобы создавать оповещения о курсах',
    'rateAlerts.error': 'Ошибка',
    'rateAlerts.updateFailed': 'Не удалось обновить оповещение о курсе',
    'rateAlerts.createFailed': 'Не удалось создать оповещение о курсе',
    'rateAlerts.success': 'Успех',
    'rateAlerts.savedSuccessfully': 'Оповещение о курсе успешно сохранено!',
    'rateAlerts.deleteTitle': 'Удалить оповещение',
    'rateAlerts.deleteMessage': 'Вы уверены, что хотите удалить это оповещение о курсе?',
    'rateAlerts.cancelButton': 'Отмена',
    'rateAlerts.deleteButton': 'Удалить',
    'rateAlerts.deleteFailed': 'Не удалось удалить оповещение о курсе',
    'rateAlerts.updateStatusFailed': 'Не удалось обновить статус оповещения',
    'rateAlerts.title': 'Оповещения о курсах',
    'rateAlerts.signInPrompt': 'Войдите, чтобы создавать и управлять оповещениями о курсах валют!',
    'rateAlerts.loading': 'Загрузка...',
    'rateAlerts.errorPrefix': 'Ошибка: {error}',
    'rateAlerts.createButton': '+ Создать оповещение',
    'rateAlerts.activeCount': '{count} активных оповещений',
    'rateAlerts.emptyState': 'Пока нет оповещений о курсах. Создайте свое первое оповещение, чтобы получать уведомления, когда курсы достигнут вашей цели!',
    'rateAlerts.active': 'Активно',
    'rateAlerts.target': 'Цель:',
    'rateAlerts.status': 'Статус:',
    'rateAlerts.created': 'Создано:',
    'rateAlerts.edit': 'Редактировать',
    'rateAlerts.delete': 'Удалить',
    'rateAlerts.cancel': 'Отмена',
    'rateAlerts.editAlert': 'Редактировать оповещение',
    'rateAlerts.createAlert': 'Создать оповещение',
    'rateAlerts.save': 'Сохранить',
    'rateAlerts.fromCurrency': 'Из валюты',
    'rateAlerts.toCurrency': 'В валюту',
    'rateAlerts.targetRate': 'Целевой курс (1 {fromCurrency} = X {toCurrency})',
    'rateAlerts.enterRate': 'Введите курс для {fromCurrency} → {toCurrency}',
    'rateAlerts.direction': 'Направление',
    'rateAlerts.direction.above': 'выше',
    'rateAlerts.direction.below': 'ниже',
    'rateAlerts.activateAlert': 'Активировать оповещение',
    'rateAlerts.status.inactive': 'Неактивно',
    'rateAlerts.status.active': 'Активно',
    'rateAlerts.status.notified': 'Уведомлено',
    'rateAlerts.conditionAlreadyMetTitle': 'Условие оповещения уже выполнено',
    'rateAlerts.conditionAlreadyMetMessage': 'Текущий курс {fromCurrency} → {toCurrency} составляет {currentRate}, что уже {condition} вашей цели {targetRate}. Оповещение сработает немедленно.',
    'rateAlerts.createAnyway': 'Создать в любом случае',
    'rateAlerts.resetTitle': 'Сбросить оповещение',
    'rateAlerts.resetMessage': 'Вы хотите сбросить это оповещение? Оно сможет сработать снова, когда условие будет выполнено.',
    'rateAlerts.resetButton': 'Сбросить',
    'rateAlerts.resetFailed': 'Не удалось сбросить оповещение',
    'rateAlerts.reset': 'Сбросить',
    ...AM_FINANCE_RU,
    ...AM_FREELANCE_RU,
    ...AM_TRANSPORT_RU,
  },
};

type LanguageProviderProps = {
  children: ReactNode;
};

const SUPPORTED_LANGUAGES: Language[] = ['hy', 'en', 'ru'];
const DEFAULT_LANGUAGE: Language = 'hy';

function isLanguage(value: string | null): value is Language {
  return value != null && SUPPORTED_LANGUAGES.includes(value as Language);
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(DEFAULT_LANGUAGE);

  useEffect(() => {
    AsyncStorage.getItem('appLanguage')
      .then((stored) => {
        if (isLanguage(stored)) {
          setLanguageState(stored);
        }
      })
      .catch((error) => {
        console.error('Failed to load language preference:', error);
      });
  }, []);

  const setLanguage = async (lang: Language) => {
    if (!SUPPORTED_LANGUAGES.includes(lang)) return;
    setLanguageState(lang);
    try {
      await AsyncStorage.setItem('appLanguage', lang);
    } catch (error) {
      console.error('Failed to save language preference:', error);
    }
  };

  const t = (key: string): string => {
    const primary = (translations[language] as Record<string, string | undefined>)[
      key
    ];
    if (primary != null && primary !== '') return primary;
    const en = (translations.en as Record<string, string | undefined>)[key];
    if (en != null && en !== '') return en;
    const hy = (translations.hy as Record<string, string | undefined>)[key];
    if (hy != null && hy !== '') return hy;
    return key;
  };

  const tWithParams = (key: string, params: { [key: string]: string | number }): string => {
    let translation = t(key);
    if (translation === key) return translation;

    Object.keys(params).forEach((paramKey) => {
      const placeholder = `{${paramKey}}`;
      const escaped = placeholder.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      translation = translation.replace(
        new RegExp(escaped, 'g'),
        String(params[paramKey])
      );
    });

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tWithParams }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
